### ISSUE TITLE
CTA for sharing in social media

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#1]
We should be able to share each area page in social media.

"Hey, I'm contributing to Rust and Servo at @Mozilla Check how easy it is to #mozactivate https://nukeador.github.io/activity-campaign/area/servo"

Even from front page: "There are easy ways to get involved with @Mozilla Do you #mozactivate ? https://nukeador.github.io/activity-campaign/"

**Comment by nukeador** [comment]
@LucyeoH ideas for CTA welcomed! ;-)

**Comment by nukeador** [comment]
Right now all initiatives pages have a sharing button for Twitter and Facebook. We can just send text to twitter, current copy sample:

"I am contributing to Rust and Servo at @Mozilla Check how easy it is to #mozactivate https://activate.mozilla.community/area/servo"

**Comment by brianking** [comment]
Might be better to have the share per activity, like:

"I'm working on the e10s add-on testing activity @Mozilla Check how easy it is to #mozactivate https://mozilla.github.io/activate.mozilla.community/area/developer-engagement/activity1"

**Comment by nukeador** [comment]
The site detects the page title and uses that for sharing, so it would be only possible if we have individual pages for individual activities.

**Comment by brianking** [comment]
I think we probably will have individual pages for individual activities.

**Comment by nukeador** [comment]
+1 for individual pages when the text is too long to live with other activities in the main area page.

**Comment by nukeador** [comment]
Removing Launch milestone since we are not going to change the current text for launch. We can revisit this after launch.

**Comment by brianking** [comment]
Can we add parameters to links?

The use case is Test Pilot, where we were discussing what the dropoff rate would be from people coming into the page vs. those who actually click on the link to install Test Pilot.

So for example, the urls would be:

{page-url}/?utm_source=twitter.com&utm_medium=social&utm_campaign=moz-community-share
{page-url}/?utm_source=facebook.com&utm_medium=social&utm_campaign=moz-community-share

**Comment by nukeador** [comment]
Where do you want to add the parameters?

You can tailor the links on the markdown pages any way you need.

If it's on the social sharing text, it's located here:
https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_layouts/page.html

**Comment by nukeador** [comment]
Parameters added. Let's close this an re-open if we need changes to wording.
