### ISSUE TITLE
About Participation page

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#10]
@geroter  suggests if we need an About Participation top menu.

@geroter the idea was to point to our wiki or have something on the site?

**Comment by nukeador** [comment]
Confirmed this is a page to talk about who we are and why we are doing this site.

**Comment by brianking** [comment]
What's the process for setting up a new page on the site?

**Comment by nukeador** [comment]
Create a .md file under _pages

You can c&p from other page to have all the top variables and adapt to the new one.

**Comment by brianking** [comment]
https://activate.mozilla.community/participation

**Comment by nukeador** [comment]
Reopening because my understanding is that we need wording here about why we are doing this site more than who participation team is (which is in the wiki)

**Comment by brianking** [comment]
I've made some updates, please review @nukeador

**Comment by nukeador** [comment]
Looks good.
