### ISSUE TITLE
Geography constrained campaigns

### ISSUE THREAD

**Issue by hmitsch** [mozilla/activate.mozilla.community#100]
# User Story
As a **Cliqz community manager** 
I want to **create an activate campaign targeting volunteers in Germany** 
in order to make sure potential contributors see only campaigns which actually relevant to them (info: the Cliqz search engine is currently focusing only on the German market)

# Job Story
When **launching a campaign**
I want to **restrict it to a certain country**
so I can attract relevant contributors instead of having a campaign which is irrelevant to 95% of the activate site audience 

# Use Case
It would be great to add a "search result quality" activity for Cliqz to activate.m.c ... however, Cliquz only really works in German/German-speaking countries.

**Comment by ankit-cliqz** [comment]
Some information about the suggested use-case/ campaign:

Cliqz (https://www.cliqz.com/en) is a web browser built on Mozilla's code base with a built-in search engine and privacy features, which currently supports German language content. Recently, Mozilla invested in Cliqz [1], and as part of introducing the Mozilla Community to Cliqz, the Activate campaign will be a sprint (Allows remote participation), involving rating of Cliqz search engine results w.r.t to the queries. This helps in improving the Cliqz Search Engine. This requires expertise in local information about Germany and of the German language. Thus, it makes sense to open this only to German speaking community and not to all communities in general. 

[1] https://techcrunch.com/2016/08/23/mozilla-invests-in-germanys-cliqz-a-private-search-browser/

**Comment by geroter** [comment]
Let me jump in with a comment here:
As it's conceived right now, Activate is **not a portal for contributors. It's a portal for mobilizers** -- people who will organize others to participate in various aspects of Mozilla.

This doesn't mean the Activate site won't become something broader, but that's currently not it's purpose.

**Why this is relevant:** Right now we will have specific relationships with most people who can mobilize on behalf of Mozilla projects (and so could just send a specific campaign for Germany or any other country to those individuals). 

Again, that doesn't mean it will be the case in the future, but I think then there's a user story that comes before "build an on-ramp for new mobilizers".

**Comment by ankit-cliqz** [comment]
@geroter  Thanks for your comment.
From what I conceived, the best way to propose such an activity could be through an activate campaign focused towards the individuals of German speaking Mozilla community, who can mobilize other groups of people to achieve this goal. One way could be to write the task activity in German, so only concerned individuals are reached. I understand that the current setup might not be ideal for this, but do you think, it will be plausible to reach out to specific language speaking sections of the community this way?

**Comment by brianking** [comment]
After further discussion it was concluded that the best approach right now is to work directly with contributors in Germany. We can re-open this at a later time if deemed necessary.

**Comment by ankit-cliqz** [comment]
Thanks @brianking. I will continue this discussion with @hmitsch offline, as to how we can realize this.
