### ISSUE TITLE
Retire the e10s and Add-ons activity

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#102]
The e10s and Add-ons activity ended on November 4. We now need to retire it.

There are a few ways we could do it.

1. Remove completely and all references to it.

2. Remove activity page but leave the title and text (not linked) on the activities page.

3. Leave as-is, but put a strong notice (see issue #72) at the top of the page that we no longer support the activity.

I prefer something like 3, but only if it is obvious that it is inactive, and that localisers are made aware that translating the page is optional (except perhaps for notice at the top).

**Comment by couci** [comment]
@brianking have we communicated this with our communities? if those are not mozactivate activities any more do you feel that we should keep them under the regular budget requests or take them out of Reps budget completely?

**Comment by brianking** [comment]
@couci we should no longer sponsor events that do this activity. And we should go one step further and tell people not to do it at all. So yes we should take it out of the Reps budget. I am working on replacement activities.

**Comment by couci** [comment]
ok @brianking please let us know so I can update the budget allocation and inform the Reps

**Comment by ioana-chiorean** [comment]
We can also announce it in the weekly call - at the non-verbal updates.
