### ISSUE TITLE
Launch comms plan

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#11]
Create and deliver the launch comms.

**Comment by nukeador** [comment]
@brianking draft happening here

https://docs.google.com/document/d/10tBSGpF3Qc_QnNXSgmQoNV90eNeXER9uHz6zSQcsCXw/edit#

**Comment by nukeador** [comment]
@brianking r?

**Comment by brianking** [comment]
r+

I would add something about where to ask questions, whether this be an existing Discourse conversation or a new one. And perhaps we should have one conversation for each activity, and on the activity page for each link to it?

**Comment by nukeador** [comment]
Probably we should first create the long post on discourse and use that link as reference for questions.

And yes, then create a new topic per activity and link them from the site.

**Comment by brianking** [comment]
\+ @geroter who is jumping in to help at launch.

**Comment by brianking** [comment]
Reps mailing list and blog went out on launch, and last week we pushed this out on more channels.

* Discourse: https://discourse.mozilla-community.org/t/activate-mozilla-campaign/10379
* Multiple groups on Telegram
* Twitter: https://twitter.com/mozillareps/status/766733019474518016

I could not make the Reps call last week, but will this week. @couci suggested we contact mentors as well to reach out to their Reps.

Promotion will need to be ongoing, and we'll need to see how to target non-Reps as well.

**Comment by brianking** [comment]
Shout out made on project call yesterday.

Am closing this and will open a new issue on the 2nd wave of comms we need to do.
