### ISSUE TITLE
Twitter Widget

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#117]
A Twitter widget on the site showing #mozactivate tweets.

Where could it go? e.g. footer to appear on all pages

How much would it affect page load times?

**Comment by MichaelKohler** [comment]
I would put this on the front page. We could use the standard twitter widget, therefore there would not be a lot of work needed.

https://twitter.com/settings/widgets/new/search?query=%23mozactivate

**Comment by MichaelKohler** [comment]
We will use the standard widget.

**Comment by MichaelKohler** [comment]
Mh, I guess the question is, where should that widget go? I would say frontpage, but there is basically no prominent place there as we want to promote the activities. @couci @LucyeoH what do you think?

**Comment by couci** [comment]
I was thinking on the right of the page similar with the mozilla.ch site. @MichaelKohler @LucyeoH thoughts?

**Comment by AlexLakatos** [comment]
where did we land on this?

**Comment by couci** [comment]
Summarizing the conversation we had on telegram:
Option 1: on the right
Option 2: over the carousel at the end of the page
Option 3: as another tile.

@AlexLakatos I am interested to see how it will look like as another tile, do you think you can give a screenshot?

**Comment by AlexLakatos** [comment]
![screen shot 2017-05-10 at 22 51 12-fullpage](https://cloud.githubusercontent.com/assets/690132/25922997/5dc37770-35d3-11e7-899d-fb1d91ee8ba0.png)

@couci This is roughly how it would look, but styling it would be a pain, because it's inside a XSS iframe.

**Comment by couci** [comment]
I have the feeling that it is actually confusing for people and might be lost @MichaelKohler what do you think?

**Comment by MichaelKohler** [comment]
I agree, let's find another place for it.. No idea from my side though.

**Comment by saidfuad** [comment]
@MichaelKohler  My few cents, i think we could keep it at the footer, on the right side and reduce the feed stream to one tweet window (for a recent tweet) or two. The footer content to remain the same but the widget to be just beside it on the right side. Hope this helps!

**Comment by couci** [comment]
I like the idea of putting it horizontally under the activities @AlexLakatos ideas?

**Comment by couci** [comment]
@AlexLakatos status update? the last idea was to replace the carousel at the end
