### ISSUE TITLE
2016 End of Year Activate Drive

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#118]
## Objective Goal: 
Reps and select local communities are updated on the Activate Campaign, and are motivated to participate before the end of the year.

## Related documents and links 
* [General Comms Doc](https://docs.google.com/document/d/10tBSGpF3Qc_QnNXSgmQoNV90eNeXER9uHz6zSQcsCXw/edit?usp=sharing)

## Item lists

Targeted drives with select communities:
- [ ] Choose communities to work with (R: @couci @nukeador)
- [ ] Create and send initial comms to communities (R: @couci @brianking)
- [ ] Do followups to provide support and get event commitments (R: @couci @brianking)

General Reps drive:
- [x] Weekly call 2016-11-24 setup (R: @couci)
- [x] Discourse post (R: @brianking)
- [x] Reps mailing list post (R: @brianking)
- [x] Tweet(s) (R: @couci)
- [x] Facebook post (R: ioana-chiorean)
- [ ] Blog post on Leaderboard and Status (R: @brianking)

**Comment by couci** [comment]
Reps weekly call planning is in here https://github.com/mozilla/Reps/issues/92

**Comment by brianking** [comment]
Project call recording: https://air.mozilla.org/reps-weekly-meeting-nov-24-2016/

**Comment by brianking** [comment]
Will break out blog post into a separate issue.
