### ISSUE TITLE
Tweaks to Web Compat activity

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#119]
After chatting with the Web Compat team, we identified a few changes that could increase the impact of the activity.

- [ ] Pull out some of the steps at https://wiki.mozilla.org/Compatibility/Guide#Reporting_a_Web_compatibility_issue and include them directly in the activity
- [ ] Be more clear on output required
- [ ] Add in alternative sources to Alexa for finding sites to test

**Comment by ioana-chiorean** [comment]
Let me know if you  need help on this. Always having a weak point for WebCompat in my heart ;)

**Comment by couci** [comment]
Closing this since we lost focus
