### ISSUE TITLE
Leaderboard says "mozillian" while only reps can be on the leaderboard

### ISSUE THREAD

**Issue by asdofindia** [mozilla/activate.mozilla.community#120]
I understand that the leaderboard is still under development, but while only reps can create reps portal event, and only reps are counted for the leaderboard, I think it's unfair to give the heading "mozillian" in the table.

**Comment by MichaelKohler** [comment]
In my opinion all Reps are Mozillians as well. But I definitely agree that this is not the best situation indeed. You can also create an event for another Mozillian and still you are the organizer on the portal. 

But this is a discussion to happen in the future again, since we will be talking about Reps, core mobilizers etc. again at the next work week. This all ties in together.

I don't really have a good suggestion regarding naming though for now :(

**Comment by asdofindia** [comment]
> In my opinion all Reps are Mozillians as well.

I'm sure I can elucidate the difference by giving analogies, but I'll defer considering the rest of your comment.

**Comment by brianking** [comment]
Yes, @comzeradd and I already discussed it. And we want to fix it. One idea was that you would be given 1 point if you *attended* an event which any Mozillian can do on the portal. However, I could see this as being problematic / easy to game as people would randomly click on events to attend.

**Comment by asdofindia** [comment]
In the long term, a fix might come from Participation Systems when the tools that are available for reps are made available for all mozillians. But in the short term, maybe we could have multiple leaderboards according to multiple criteria and a short note at the top stating the caveats.

Also, we can think of a feature on the portal whereby organizer can confirm the participation of an "attendee". (This can go together with micro-achievements and open badges)

**Comment by couci** [comment]
Right now there is no fix on counting mozillians with point system cause the as @brianking mentioned the system can be easily tricked. On having multiple leaderboards, we are having this conversation on issue #131 
So I think we should close this one

**Comment by asdofindia** [comment]
Although the discussion on #131 is still revolving around "reps" and the very point of this issue was about "mozillians". Anyhow.
