### ISSUE TITLE
Roadmap Updates

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#122]
Here are a couple of things that have come up in conversations.

- [ ] Better show the status of retired (e.g. e10s) and de-emphasised (e.g. Test Pilot) activities
- [ ] Be more explicit on how to suggest new activities

**Comment by MichaelKohler** [comment]
The same will go for https://github.com/mozilla/activate.mozilla.community/issues/132

**Comment by MichaelKohler** [comment]
Roadmap is updated with my open PR.
