### ISSUE TITLE
Support Right-To-Left Layouts

### ISSUE THREAD

**Issue by anefzaoui** [mozilla/activate.mozilla.community#124]
I think implementing RTL layout will encourage our Arabic, Persian, Urdu and Hebrew communities to get involved with Activate Mozilla, and get their members who aren't necessarily fluent in English rolling as well.

I'm on working on a PR.

It won't have Arabic localization, but RTL implimentation will be bedrock of having those locales live on activate.mozilla.org.

**Comment by ioana-chiorean** [comment]
🙌

**Comment by brianking** [comment]
Over to @comzeradd for review.

**Comment by MichaelKohler** [comment]
Once the Pontoon changes are live, I'll post in the PR to make sure we are ready for this :)

**Comment by MichaelKohler** [comment]
This will need more work given that https://github.com/mozilla/activate.mozilla.community/pull/205 will be merged soon. We went back to markdown files, so we will take a PR that takes the design changes into account as well as uses the Markdown approach (no xliff files specifically).
