### ISSUE TITLE
Add Swag Procedure to FAQ

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#127]
Add link and explanation for https://wiki.mozilla.org/Participation/Projects/Activate_mozilla/Local_Swag to the FAQ.

**Comment by couci** [comment]
Yes I think this makes sense, @MichaelKohler do you need text for this?

**Comment by MichaelKohler** [comment]
Yes, a question and an answer would be great. I can add it once I have that.

**Comment by couci** [comment]
Here is how it looks right now: https://pageshot.net/x7QqKMSz60LQOPJN/activate.mozilla.community
Let's take out swag from the initial question and make it: "Can I request budget for these activities?"
Everything should stay the same except the line: assets... that should be removed
Under it let add:
"Can I request swag for these activities?"
Answer: in the case you need swag you can either request via the swag request form (link) or produce on your own (above link)
In both cases your request will be evaluated from the bug wrangler before approved
