### ISSUE TITLE
Activity pages urls naming

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#13]
@brianking we need activity pages to follow the current url naming.

I see:

https://activate.mozilla.community/area/devengage/webcompat-sprint
https://activate.mozilla.community/area/devengage/rust-hack
https://activate.mozilla.community/area/firefox/test-pilot

But /area/devengage doesn't exist (it's /area/developer-engagement) neither /area/firefox (right now it's /area/test-pilot)

**Comment by brianking** [comment]
I changed them because they were shorter urls. Is you preference to go with the old or the new?

**Comment by nukeador** [comment]
I prefer the old ones. Maybe we can remove the /area/ part to make it shorter.

**Comment by brianking** [comment]
/area/ removed and urls are now set.

https://activate.mozilla.community/developer-engagement/webcompat-sprint
https://activate.mozilla.community/developer-engagement/rust-hack
https://activate.mozilla.community/experiments/test-pilot
