### ISSUE TITLE
Launch WebExtensions Activity

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#133]
The preparation for the WebExtensions activity is in a mature stage. It needs final review and launch. This has primarily been worked on by @caitmuenster on the Add-ons team.

Draft activity: https://docs.google.com/a/mozilla.com/document/d/1NAyCjn1iINZH7cIWlEndbFNMoR93FLOrNoeIKFPR7tE/edit?usp=sharing

**Comment by caitmuenster** [comment]
Thank you, Brian!

**Comment by iamVP7** [comment]
Would like to contribute here.

**Comment by viswanathamsantosh** [comment]
I would love to help in this activity planning!

**Comment by caitmuenster** [comment]
Hey all! It looks like the final review is complete.

**Comment by couci** [comment]
thank you @caitmuester :)
@AlexLakatos @MichaelKohler can we have this in markdown so we have it in our website?

**Comment by MichaelKohler** [comment]
Can this go live once I've done this? Or do you have any specific date in mind? I can start working on it and once that question is clear, we can merge the Pull Request.

**Comment by caitmuenster** [comment]
I think this is good to go live as soon as it's in markdown!

**Comment by MichaelKohler** [comment]
@caitmuenster another question, there is an overview at https://activate.mozilla.community/activities/ . As far as I see, the doc doesn't provide a nice short description of the activity that we could put there. Ideally this should be between 2 or 3 lines and make the activity really tempting to open :) Do you think you could provide a short description like that?

Example from WebVR:

> A-Frame is a web framework for building virtual reality experiences, making it easy for anyone to get involved with virtual reality. Run events to onboard developers into 3D and write some great demos. This will advance WebVR, an open platform for virtual reality that leverages the Web. Find out more.

**Comment by caitmuenster** [comment]
@MichaelKohler Sure thing! How about: 

Add-ons provide a safe, simple, and powerful way to personalize your browsing experience. With WebExtensions APIs, it’s easier than ever to create extensions that can be easily ported to Firefox, Chrome, Edge, and Opera. Through this activity you’ll help connect new developers with an opportunity to create add-ons to solve real problems and make their lives and the web better.

**Comment by MichaelKohler** [comment]
Sounds catchy, I'll take this one :)

**Comment by caitmuenster** [comment]
@MichaelKohler Andreas' eagle eyes caught some typos in the google doc a few minutes ago. Any chance you could incorporate them into the markdown? Sorry for giving the go-ahead a titch too quickly!

**Comment by MichaelKohler** [comment]
As far as I see this is just deleting "Add-on" in the title and the discussion about the IRC channel. No biggies, so ping me once you've reached a decision for those two points and I'll put those in. You can also change the doc as long as you tell me which paragraphs changed.

**Comment by MichaelKohler** [comment]
Quick update: Caitlin is working on a Discourse post that needs to be linked in the activity. Once I have that link, I'll create a PR.

**Comment by MichaelKohler** [comment]
PR opened here: https://github.com/mozilla/activate.mozilla.community/pull/171
