### ISSUE TITLE
Additional event metrics for Rust

### ISSUE THREAD

**Issue by dvigneshwer** [mozilla/activate.mozilla.community#134]
Listing down few metrics for Rust events which can help in measuring success of the event and are better sources for longer term developer engagement

- People creating profile in [rustaceans](http://www.rustaceans.org/). [Example profile](http://www.rustaceans.org/dvigneshwer) 
- People joining their [regional rust user group](https://www.rust-lang.org/en-US/user-groups.html) 
- Following [rust reddit channel](https://www.reddit.com/r/rust/)
- Following [rustlang](https://twitter.com/rustlang) & [thisweekinrust](https://twitter.com/thisweekinrust) twitter accounts  
- Joining [rust discourse](https://users.rust-lang.org)

Would be ideal to add it to the output section of [rust-hack](https://activate.mozilla.community/rust-hack/)

cc @couci @brianking

**Comment by brson** [comment]
Simply counting the attendees at events seems like an easy and meaningful number. If we could aggregate the number of people attending Rust meetups, and watch that number go up, seems good. And with the number of meetups Rust has, and the importance of meetups to Rust culture, that would be a good number to tout.

We could e.g. reach out to all known Rust meetup organizers and politely ask them to submit estimates after their events, then compile those into periodic reports.

**Comment by couci** [comment]
on the reps side we can count attendees from the portal and this is a metric easily tracked via community analytics
@brson on Rust meetups I guess you're using meetup to make those public?
@dvigneshwer I really like your ideas, how do you think we are going to tie those numbers to events related to us?
@bacharakis is also thinking around metrics on Rust so I would like to ask his ideas as well.

**Comment by dvigneshwer** [comment]
In the reps site event form, we can add these as event metric which will be very specific to rust events.

- Number of attendees creating a rustaceans profile?
- Number of attendees joining the rust users discourse channel?
- Number of attendees tweeting to rustlang about a feature of rust?
- Number of attendees joining the Reddit channel?
- Number of attendees interested in creating a crate?
- Number of attendees interested in conducting a rust event?

These event metrics will help in understanding the effect of rust event in both short and longer term.

**Comment by couci** [comment]
I think we can have it as an experiment, though those would be self reported numbers and not automated. @dvigneshwer do you think we should ask specific usernames to be added on the report?

**Comment by MichaelKohler** [comment]
@brson this here is about activate.mozilla.community, for overall meetups about Rust, it might be worth looking at https://github.com/mozilla/participation-metrics-org . 

@dvigneshwer of course we could add those to the event report, but that might clutter the dropdown quite a bit. However, if those numbers are benefitial, let's do this. That could then also be analyzed through Community Analytics.

@couci regarding user names, we could ask to put them in the "notes" section of the metrics.

**Comment by dvigneshwer** [comment]
@couci usernames could be really useful but I am not sure if we have enough analytics power of generating reports which could tell how active a particular user joining the rust forums from the event has been, this would require a lot of data crunching. IMHO collecting usernames for the report is not giving us many insights unless we have an advanced analytical system.

Down the line, it is very natural that not all the participants of an event are gonna pursue rust language for application development in their day to day life, even the above event metric will only help in making sure that all the rust user channels are introduced to the participants or not. Rust being a programming language requires a certain learning curve and self-motivation from the participants also.

However, I feel the collecting the usernames can be used in establishing longer developer engagement by introducing the new enthusiastic rust developers from the event to open projects begin developed on rust who require community contribution, this is a win -win situation for both developer and community as both are mutually benefiting but this would require the data collection of listing region wise rust open projects.

@MichaelKohler yeah the numbers achieved through those event metrics will be generic and really useful to measure the success of rust evangelism in a particular region.

Have shared these feedbacks already to @brson

**Comment by couci** [comment]
I like @dvigneshwer we should try this by starting gathering the usernames. Yes, following their contribution path might be difficult but it's a step forward

**Comment by couci** [comment]
Those metrics were approved to be added on the reps portal. Thanks all for the hard work, I am closing this one
