### ISSUE TITLE
Spanish (es) localization

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#14]
Tracking issue for Spanish localization.
- [ ] Front page
- [ ] FAQ
- [ ] Roadmap
- [ ] Participation
- [ ] Developer engagement
- [ ] Experiments

**Comment by ioana-chiorean** [comment]
What other languages are needed?

**Comment by nukeador** [comment]
The content is not final yet, so we can't start localizing.

Once it's final we will have Spanish and Portuguese as P1 and German and French as P2.

In any case, people is free to localize it in other languages anytime, but these are going to be the ones we are going to push for from our side to align with our focus communities.

**Comment by ioana-chiorean** [comment]
👍 ok. got it. 🙇

**Comment by ziww** [comment]
I'd love to help with PT-BR l10n.

**Comment by womozci** [comment]
I would like to help with En-FR l10n.

**Comment by brianking** [comment]
As the content is now stable, is there a plan to finish the es translation?

**Comment by deimidis** [comment]
@brianking we are coordinating this with Mozilla Hispano community. Will push there :)

**Comment by tuxlan** [comment]
Hi
I'm from Mexico. I would like to help with Spanish localization

**Comment by gaby2300** [comment]
Hi,
I can help with Spanish too!

**Comment by gaby2300** [comment]
It would be helpful to know the content to be localized so we can share it between us

**Comment by nukeador** [comment]
All the content is under the /es/ folder

https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_pages/es

**Comment by pochy-ja** [comment]
What is the state of this translation?, somebody work on this?

**Comment by MichaelKohler** [comment]
Once all the translations are on Pontoon, translating will be easier. Will update this issue once it's done.

**Comment by MichaelKohler** [comment]
Even though there are quite a lot of translations in there now, I think a few things are missing.

Could somebody review the content of the following 3 folders and make a PR against this repo in case there are more translations needed? Thanks!

https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_pages/es
https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_data/l10n/es.yml
https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_includes/es

**Comment by couci** [comment]
Hey all,
let us know if anyone is up on the translations otherwise we will need to close this issue and remove the partial translations

thanks

**Comment by Josexv1** [comment]
@couci i will be translating the new activities, will create a new list of things being translated by me. As my old translation is a bit outdated.

**Comment by MichaelKohler** [comment]
We are currently working on a refresh of the Activate page. This project is in its early stages, but what I can say now is that localization improvements (Pontoon) will be a big part of it. I'm closing this as it will be considered in the refresh. Once we will talk about about what locales to enable to be translated we will revisit all localization issues in this repository, so there is no need to create a new request somewhere.
