### ISSUE TITLE
New logo for activate based on new mozilla style guides

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#140]
We are aiming for a more appealing logo for activate once we have the style guides for mozilla's new logo

**Comment by couci** [comment]
@elioqoshi do you think it's time to move this forward? Should we open an issue on the open design repo?

**Comment by elioqoshi** [comment]
Thanks for bringing this to my attention. Yeah let's open one on the Open Design trepo

**Comment by couci** [comment]
Logo has been added here: https://github.com/mozilla/OpenDesign/issues/132
@MichaelKohler should we move this to P1 once you're done with the dashboard?

**Comment by MichaelKohler** [comment]
Yes, if somebody wants to start before, feel free :)

**Comment by MichaelKohler** [comment]
Implementation of this is tracked in #283. Thanks for the logo, Elio!

**Comment by elioqoshi** [comment]
Will add also a horizontal version, but will post in that thread :)
