### ISSUE TITLE
Replace Header image and write a bigger explanation on what Activate is

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#146]
On the frontpage, we should replace the header image with a better representing image. Also we should write a text that better explains what Activate is. This should not be too much, but should capture more than "A campaign for Mozillians around the world to have impact in areas key to Mozilla’s mission."

**Comment by MichaelKohler** [comment]
@couci could you provide the text for this?

**Comment by couci** [comment]
I was thinking someone between the lines of what we've already created:
A campaign that provides guidance to mobilizers on how to recruit contributors and create community around meaningful Mozilla projects

**Comment by Srushtika** [comment]
I think the image would be great if it's a collage of various MozActivate activities (representative pictures) done till now (by various communities over the world) , with a color or b/w filter on the collage to make it look even! 

But I'm not sure if a collage looks good for a header 😀

**Comment by Srushtika** [comment]
@couci 's suggestion for the text is great. Also, sharing something I had wrote up a long time ago. You might wanna use some excerpts :
The MozActivate campaign aims at the grassroots of Volunteer contributions, thus empowering the newest of contributors with the simplest of tools to contribute to the most impactful areas!

**Comment by hmitsch** [comment]
Here is my favorite for the header image: https://thenounproject.com/Becris/collection/startup-business-concept/?oq=activate&cidx=65&i=476622

**Comment by couci** [comment]
I really like @Srushtika 's line, @MichaelKohler what do you think?

**Comment by MichaelKohler** [comment]
I like it too! I've merged her line with some of the FAQ. @couci What do you think?

"The Activate Mozilla campaign aims at the grassroots of volunteer contributions. We want to bring more clarity on what are the most important areas to contribute to at Mozilla right now, and provide clear steps on how to get involved right away, thus empowering the newest of contributors with the simplest of tools to contribute to the most impactful areas. These are presented in the form of activities."

**Comment by MichaelKohler** [comment]
For the header image, I have looked for some pictures, but didn't really find something I *really* like. Some ideas:

https://farm2.staticflickr.com/1448/24009148094_d1a1be14ec_k_d.jpg <-- still a group picture, but less creepy than the current one

https://farm9.staticflickr.com/8296/29659283086_2c0d3fbcae_k_d.jpg <-- not really a "working environment" that we would expect from the activities, but I kind of like this picture.

Any other ideas?

**Comment by Srushtika** [comment]
Suggestions !
I really like this one for the header image: https://flic.kr/p/Jge56d
Also, this: https://flic.kr/p/JCVMC1

**Comment by kelimuttu** [comment]
Hey guys, 

just trying to capture @Srushtika's idea [here](https://www.canva.com/design/DACOENKp-bU/dmv5npIhIM74Z8dxEBL8-w/view?utm_content=DACOENKp-bU&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton).  What do you guys think?

**Comment by Srushtika** [comment]
Hey @kelimuttu! How about having the color theme the other way round? i.e. The background with a dark grey filter and the text being white!

**Comment by MichaelKohler** [comment]
This looks great! I agree with Srushtika though, that might make it easier to read.

We could also just go with "Activate" and put the description below the header. Though we would need to make sure that it's still above the fold. 

In any case, I will only need the background image in the end. I'll then pop the text above it so it is not integrated in the header. This way we will be able to localize it.

**Comment by couci** [comment]
Replying back on @MichaelKohler about the message, on a second thought since we are moving to the mobilizers role, let's capture that on the messaging. Suggestion:
"The Activate Mozilla campaign aims at the grassroots of volunteer contributions. We want to bring more clarity on what are the most important areas to contribute to at Mozilla right now by providing guidance to mobilizers on how to recruit contributors and create community around meaningful Mozilla projects"
@MichaelKohler @Srushtika what do you think?

**Comment by MichaelKohler** [comment]
yeah, makes sense. Though it's not really a "moving to" but a "making clear of" ;)

**Comment by couci** [comment]
yes agreed :D

**Comment by kelimuttu** [comment]
@Srushtika Cool idea. Is [this](https://www.canva.com/design/DACOENKp-bU/dmv5npIhIM74Z8dxEBL8-w/view?utm_content=DACOENKp-bU&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton) capture what you have in mind? 

@MichaelKohler I might need a size/image resolution before I convert it. Can you provide it?

Also, if you guys have any specific images you want to include in the collage, feel free to put them here so I can include them in the collage.

**Comment by MichaelKohler** [comment]
@kelimuttu the current image is 1125px × 750px, I think it would be great to have the same width (1125) as well. For the height we will see how it will look, otherwise we could still remove one row from it if we need to. Do you think that would be possible?

**Comment by kelimuttu** [comment]
That's absolutely doable. I'll do it tomorrow then.

**Comment by couci** [comment]
Dumping some more pictures here:
https://www.flickr.com/photos/124547092@N05/31167104363/
https://www.flickr.com/photos/124547092@N05/31099959774/
https://www.flickr.com/photos/mozillaindore/30635168534/

and https://scontent-fra3-1.xx.fbcdn.net/v/t31.0-8/14692124_547915208737075_5276103075568170891_o.jpg?oh=1092d4509f35471ad5961f8e06b97725&oe=593EC5B5 ( @Srushtika we will need your permission for it :P)

I also like the picture that @MichaelKohler got with Ioana and Brian working together

**Comment by Srushtika** [comment]
@kelimuttu I was thinking of a darker version like [this](https://www.flickr.com/gp/136974235@N05/1jd468) , also with fewer and bigger images. The ones I used here are not relevant -  just picked from google.

@couci Of course, you may use it (I'll be famous ;))

**Comment by kelimuttu** [comment]
I just add 2 pictures on [the repo](https://github.com/mozilla/activate.mozilla.community/commit/ce5313cd270489d03aa29269bbc90f014cee1446). I leave the color original so Michael can play with the filter. Let me know if it need to be changed.

**Comment by MichaelKohler** [comment]
Thanks, I'll play around with them!
