### ISSUE TITLE
Improve FAQ menu visual

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#148]
Currently the Activity Detail menu and the FAQ menu is not as beautiful and helpful as it can be.

Let's come up with a better way to show those menus.

**Comment by MichaelKohler** [comment]
Depending on the result of https://github.com/mozilla/activate.mozilla.community/issues/151 the activity detail menu (TOC) issue might be fixed by then. The FAQ will still stand though.

**Comment by MichaelKohler** [comment]
@couci should we just remove the menu for the FAQ page? or is it too clean then? any design idea?

![screen shot 2017-02-26 at 00 15 12-fullpage](https://cloud.githubusercontent.com/assets/330324/23335598/b06f6024-fbb8-11e6-912f-045ea23dad61.png)

**Comment by couci** [comment]
Remove definitely no, it contains info necessary for the people taking the activities.
I don't really have a design idea for it to be honest other than putting it at the end of the menu

**Comment by MichaelKohler** [comment]
Oh, sorry. I didn't mean to remove the whole page. Sorry for the wrong phrasing.

What I meant is the "Table of Content" menu at the top of the FAQ page which currently doesn't look that good. Do we need it? If so, do you have an idea on how we could style it?

**Comment by MichaelKohler** [comment]
On a second thought, let's see how the menu in the activity detail works out (currently the whole activity detail page is being worked on in terms of design). Maybe we can adapt that for the FAQ page then.

**Comment by Ryuno-Ki** [comment]
What about making it an accordion? Like mobile wikipedia. The replies could be expanded on demand.

**Comment by Ryuno-Ki** [comment]
Found an example for it at https://www.tawk.to/

**Comment by MichaelKohler** [comment]
Renamed the title so it is only about the FAQ menu, since the activity detail menu will be reworked anyway in #151 .

**Comment by MichaelKohler** [comment]
This will be covered by this PR as well, therefore assigning to Laka as well:

https://github.com/mozilla/activate.mozilla.community/pull/205#discussion_r106297220

**Comment by MichaelKohler** [comment]
Done with the merge of the new activity detail view.
