### ISSUE TITLE
Discourse topics for launch

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#15]
Create a new topic for each one and link it back from the page.

- [x] [Roadmap](https://activate.mozilla.community/roadmap)
- [ ] [Rust Hack and Learn](https://activate.mozilla.community/developer-engagement/rust-hack)
- [ ] [Web Compatibility Sprint](https://activate.mozilla.community/developer-engagement/webcompat-sprint)
- [ ] [Install Test Pilot](https://activate.mozilla.community/experiments/test-pilot)

**Comment by brianking** [comment]
@nukeador by Roadmap, do you mean a general post introducing the campaign?

What category will these go under ... Participation?

I'm thinking it might be good if I post these, just because I post less on Discourse. Can you make a first draft of the posts? Then I'll review and post later today.

**Comment by nukeador** [comment]
We are using the Participation Leaders discourse.

I created one for the roadmap (sorry, I didn't read your comment about you creating them):

https://discourse.mozilla-community.org/t/activate-mozilla-roadmap/10068

Can you create the rest with the same format "Activate Mozilla - Activity Name"

Text: "This is a topic to talk about the Activity Name activity as part of Activate Mozilla.

(Work in progress)"

**Comment by brianking** [comment]
I'm wondering why Participation Leaders, and not Participation. I think we want these to appeal to as broad a group of Mozillians as possible.

**Comment by brianking** [comment]
Posts are up:

* https://discourse.mozilla-community.org/t/activate-mozilla-dive-into-rust/10073/1
* https://discourse.mozilla-community.org/t/activate-mozilla-web-compatibility-sprint/10074/1
* https://discourse.mozilla-community.org/t/activate-mozilla-install-test-pilot/10075/1

I added links to them in the activities pages.
