### ISSUE TITLE
Better flag retired activities

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#150]
Currently retired activities only have a small alert at the top of their description. We should make this more noticeable to make sure retired activities are not run anymore.

<img width="1022" alt="screen shot 2017-02-20 at 14 29 31" src="https://cloud.githubusercontent.com/assets/330324/23126865/032da724-f779-11e6-8045-81cf0692928b.png">

**Comment by DineshMv** [comment]
@MichaelKohler  
How about implementing the same '.retired' to every section of the page ? 
(Like this!)
![screenshot from 2017-02-25 08-44-49](https://cloud.githubusercontent.com/assets/10209762/23327703/d35c9b88-fb36-11e6-8423-d09e8c9497f7.png) 

or

 just increasing the opacity of the content like this ? 
The top ribbon in bold color says the activty is retired and the bottom content appears with less opacity. 
![screenshot from 2017-02-25 08-58-29](https://cloud.githubusercontent.com/assets/10209762/23327804/de680b8c-fb38-11e6-82cd-58e46784c94d.png)

**Comment by MichaelKohler** [comment]
I think both of them are good options. There might still be people who want to read them, so I think option 1 gives better contrast.

Would you like to work on this? Just note that we will change the design of the activity details in #151. So that fix here would only be temporary :)

**Comment by DineshMv** [comment]
No problem, I work on it. In case if the new design gets delayed more time than expected.

**Comment by MichaelKohler** [comment]
Done with the merge of the new activity detail view.
