### ISSUE TITLE
Better visuals for activity details

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#151]
Currently the activity details look kind of boring. We should make these details beautiful.
One design by Christos: https://drive.google.com/file/d/0Bwl5PnEA3iBfWFdpSVNtcDZuN281cnpLbmlVYzhJaEdIMS04/view 

Let's adapt this proposal and make it beautiful! :)

<img width="551" alt="screen shot 2017-02-20 at 14 30 54" src="https://cloud.githubusercontent.com/assets/330324/23126913/3948681c-f779-11e6-95dd-96682f158c93.png">

**Comment by MichaelKohler** [comment]
https://mozillacampusclubs.github.io/becomeVRRockstar/

**Comment by couci** [comment]
I really like @bacharakis idea and I think this is an important piece if we want to make the website more appealing.
@MichaelKohler @AlexLakatos do we have a timeline for this one?

**Comment by MichaelKohler** [comment]
This has been done!
