### ISSUE TITLE
Better overview of activities / remove categories

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#152]
The overview of activities is currently not very appealing. This is due to the following problems:

* Categories do not really match their content
* There are no images on the activities

**Todo in this issue:**
* Remove the categories
* Add tags to activities based on interest that is needed for these
* Display all activities like the boxes on https://leadership.mozilla.community/
* This then should also be displayed on the frontpage instead of the categories (but without the retired ones)
* See also https://github.com/mozilla/activate.mozilla.community/issues/149 for the header image

<img width="1136" alt="screen shot 2017-02-20 at 14 41 08" src="https://cloud.githubusercontent.com/assets/330324/23127328/f1244248-f77a-11e6-8532-6dc4fceb88f9.png">

**Comment by MichaelKohler** [comment]
Displaying this on the frontpage as well might get tricky. This would require us to do a language dependant include, or is there a way to include a page in index.md? Couldn't find a solution on the web for this yet. 

I'll start with the activities page first and then we can see what we want to do with the frontpage.

**Comment by geroter** [comment]
I think that you could even just go with a slightly beautified version of the activities page on the front page, maybe with a horizontal 3-column layout. Even if this needed to be manually updated to begin?

**Comment by MichaelKohler** [comment]
@geroter not sure what you mean by that. Do you have an example? Do you mean something like a slider?

**Comment by geroter** [comment]
Was thinking of something like the bottom section here:
https://toolkit.mozilla.org/

Similar to what you referenced with the Leadership Toolkit.

Basically, the site could have a one or two sentence purpose explanation, then the 5-6 active initiatives (in boxes 3 across), then maybe something something that highlights what's new (like that bottom yellow slider thingy on the toolkit site).

Thoughts?

**Comment by MichaelKohler** [comment]
Yes, that is a good idea! I'll play around with it once I get to it.

**Comment by MichaelKohler** [comment]
Current work in progress:

![screen shot 2017-02-25 at 21 54 43-fullpage](https://cloud.githubusercontent.com/assets/330324/23334715/20a3cb14-fba5-11e6-9061-e7d8c4603ac5.png)

![screen shot 2017-02-25 at 21 54 51-fullpage](https://cloud.githubusercontent.com/assets/330324/23334717/257bb7aa-fba5-11e6-9b04-ca0902b6db7c.png)

**Comment by MichaelKohler** [comment]
Current WIP for the frontpage:

![screen shot 2017-02-25 at 22 07 31-fullpage](https://cloud.githubusercontent.com/assets/330324/23334802/d926f7fa-fba6-11e6-831b-b9d368f0ecf6.png)


TODO:
- [ ] Add slider as suggested by George

**Comment by MichaelKohler** [comment]
Slider added (it will change every 6 seconds). I've omitted the "next"/"previous" buttons for now, since I couldn't find a way to make them look nice. It looks kind of weird to have them at the edges like on toolkit.mozilla.org. Any ideas?

Could I please get feedback on the following screenshots? @couci @AlexLakatos 

![screen shot 2017-02-26 at 20 24 21-fullpage](https://cloud.githubusercontent.com/assets/330324/23342852/d3e454f2-fc61-11e6-80a3-34d880e80dcb.png)

![screen shot 2017-02-26 at 20 24 31-fullpage](https://cloud.githubusercontent.com/assets/330324/23342854/d92f3a3a-fc61-11e6-8591-fd02189ca249.png)

![screen shot 2017-02-26 at 20 24 41-fullpage](https://cloud.githubusercontent.com/assets/330324/23342855/e102d604-fc61-11e6-8ec1-55dd97ea9072.png)

**Comment by couci** [comment]
I like it, my feedback is you put them in categories though those don't appear anywhere else but the on the landing page. Should we add a categories option on the upper header?

P.S Personal opinion: I don't like that blue, can we choose a colour from the new official mozilla colours?

**Comment by MichaelKohler** [comment]
Thanks for the feedback. I'd love to get a second opinion as well, @AlexLakatos promised to give feedback today as well :)

> I like it, my feedback is you put them in categories though those don't appear anywhere else but the on the landing page. Should we add a categories option on the upper header?

Filed #180.

> P.S Personal opinion: I don't like that blue, can we choose a colour from the new official mozilla colours?

Filed #181.

**Comment by MichaelKohler** [comment]
@couci do you want me to create a PR for this? We can still improve this when we see something we want to change.

**Comment by couci** [comment]
yes please go ahead

**Comment by MichaelKohler** [comment]
Fixed by https://github.com/mozilla/activate.mozilla.community/commit/9ac6e4d8f7f2aabb05c14600b4dfc8fc4f6d68be
