### ISSUE TITLE
Add link to Reps Portal

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#156]
From @emmairwin in https://github.com/mozilla/activate.mozilla.community/issues/70#issuecomment-250235952:

> Find-ability - It took a while to find the 'Activate Mozilla' website, Google didn't give it to me in the top searches ( I tried activity campaign Mozilla, activate Mozilla. I also looked under participation in Discourse, but finally found it via search in Participation Leaders. The post themselves don't link to a landing page, which makes it harder to 'look around' at other options.

**Comment by geroter** [comment]
Two quick reactions to this:

1) Seems sensible to work on in-site improvements in navigation ... especially helping mobilizers find initiatives that are a priority

2) I don't think solving the findability of the site makes sense to work on now from a search perspective. We literally know the names and email addresses of every single person who we would want to know about this. So higher touch makes much more sense than anything else.

Some ideas:
- linking off the front of the Reps portal
- having a pinned post on Discourse
- regular emails ... maybe this is a weekly feature in the Reps meeting and comms

**Comment by MichaelKohler** [comment]
We agreed to put this on the Reps portal for now.

**Comment by MichaelKohler** [comment]
what should it be called? MozActivate? Mozilla Activate? Activate Mozilla?

<img width="1012" alt="screen shot 2017-04-06 at 23 12 25" src="https://cloud.githubusercontent.com/assets/330324/24775874/eca28384-1b1e-11e7-8f31-7558b1873dd9.png">

**Comment by couci** [comment]
I think Activate Mozilla is better

**Comment by MichaelKohler** [comment]
PR opened here: https://github.com/mozilla/activate.mozilla.community/pull/216

**Comment by MichaelKohler** [comment]
PR for Reps portal created: https://github.com/mozilla/remo/pull/1345

**Comment by MichaelKohler** [comment]
PR has been merged, with the next deploy this issue will be solved.

**Comment by MichaelKohler** [comment]
This has been deployed and is live now.
