### ISSUE TITLE
Detail the need or not of budget for activities

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#18]
We need a clear note on all activities detailing if they are zero-budget activities and events.

This is a blocker before launch for Council, review team and mentors.

**Comment by brianking** [comment]
Done. I added bolded text for this in the Format section of each activity. I also added a question/answer to the FAQ.

**Comment by deimidis** [comment]
Thanks Brian, I doubt I could write english better than you, but maybe it's more clear if this phrase:

These are no budget activities / events, meaning that Mozilla

Says:

These are zero budget activities / events, meaning that Mozilla

Or if we say zero budget sounds bad?

**Comment by brianking** [comment]
Zero budget sounds better .. I will change it.

**Comment by couci** [comment]
Can we make sure that there is a mention for swag requests too? Because people will open those

**Comment by nukeador** [comment]
@couci This is something @geroter and @brianking are working in sync with Council to provide better clarity and policy for everyone.

**Comment by brianking** [comment]
This has morphed a bit, and the conversation has moved to #21 (essentially a dupe). I'm closing this one, let's continue over there.
