### ISSUE TITLE
Make activities searchable/filterable

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#180]
Once #152 is landed, we probably want to make the activities sortable/filterable 

* by name
* by tag ("Programming", "Testing", etc)

I think this should be done with a dropdown above the activities.

This is not a priority as long as we do not have a massive amount of activities.

**Comment by MichaelKohler** [comment]
@AlexLakatos any idea on technology-wise possibilities on how to do this easily with Jekylls?

**Comment by Ryuno-Ki** [comment]
I'd do it in JavaScript client-side.
Since you've [put the tag next to](https://github.com/mozilla/activate.mozilla.community/blob/9ac6e4d8f7f2aabb05c14600b4dfc8fc4f6d68be/_includes/activities.html#L18) `.activity-card` you can check the lowercased input against it to `display: none;` non-matching cards.

Filtering for the name requires a match against `.activity-card h2` textContent.

Shall I work on a PR?

**Comment by MichaelKohler** [comment]
Sounds like a good stategy to me, thanks for the input!

Since you already looked into it, I'd love to see your PR!

**Comment by Ryuno-Ki** [comment]
I'm working in https://github.com/Ryuno-Ki/activate.mozilla.community/tree/issue-180-filterable-activities

Shortly before I committed my code I noticed, that jQuery is included. (Albeit not at that point in time, where my script would be executed)

Shall I refactor to use it?

**Comment by MichaelKohler** [comment]
I'm happy with everything that is vanilla, we might even want to get rid of jquery at some point to make the website even smaller. So no, no need to refactor it.

**Comment by Ryuno-Ki** [comment]
Since I'm running Linux only I can only test against Firefox, Chromium and Opera.

Someone should test against IE/Edge, Safari and on mobile before merging.

**Comment by MichaelKohler** [comment]
Sure, I can have a look. I'll do that once the PR is created.

Would you mind to test it against the responsive view of Firefox to at least make sure that the mobile resolution is okay per se not taking into account mobile browsers quirks?

**Comment by Ryuno-Ki** [comment]
I can do that.

**Comment by MichaelKohler** [comment]
@Ryuno-Ki what's the status here? :)

**Comment by Ryuno-Ki** [comment]
I was sick, so too tired to work on it.
I'm trying to look into it this weekend.

What's basically missing is
* a `<label>` for the `<input />`,
* fine transitions (ideally per CSS) and
* testing everything on mobile + desktop in several web browsers.

**Comment by Ryuno-Ki** [comment]
I've opened https://github.com/mozilla/activate.mozilla.community/pull/207.

Tested on:
* desktop: Firefox, Chromium, Opera
* Android: Firefox, Chrome

I can squash the commits before accepting the PR if you want. But I think, GitHub's Web UI offers that as well.
