### ISSUE TITLE
Re-evaluate color scheme

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#181]
Proposal from Konstantina:

"can we choose a colour from the new official mozilla colours?"

This would mostly be for the navigation, links and table headers. We should also think about the color of the footer. If we go into that direction, the footer probably should be black to match the general style of the new logo.

**Comment by MichaelKohler** [comment]
I'll play around with those colors once I get to it to provide a few examples.

**Comment by MichaelKohler** [comment]
I've played around with the colors, and not a lot fit very well as-is.

I like the blue one (first one, not the neon one), and maybe the orange one is not too bad as well. Of course we would need to change a few other things as well like text color and general adaption of the "highlight backgrounds". What do you all think?

![screen shot 2017-03-03 at 01 15 49](https://cloud.githubusercontent.com/assets/330324/23533216/8e2ed9bc-ffb0-11e6-98c7-fa75fbd6416f.png)

![screen shot 2017-03-03 at 01 16 46](https://cloud.githubusercontent.com/assets/330324/23533226/a30eca40-ffb0-11e6-89d2-887b98469f6c.png)

![screen shot 2017-03-03 at 01 17 16](https://cloud.githubusercontent.com/assets/330324/23533229/a7deea32-ffb0-11e6-87a5-e2a7a81f7e6e.png)

![screen shot 2017-03-03 at 01 17 44](https://cloud.githubusercontent.com/assets/330324/23533231/af44894e-ffb0-11e6-9e05-5c9e2eb0f76a.png)

![screen shot 2017-03-03 at 01 18 17](https://cloud.githubusercontent.com/assets/330324/23533233/b46902d8-ffb0-11e6-96e2-8067949b15a0.png)

![screen shot 2017-03-03 at 01 18 41](https://cloud.githubusercontent.com/assets/330324/23533236/ba91cad2-ffb0-11e6-8a25-788e7da403a2.png)

![screen shot 2017-03-03 at 01 19 06](https://cloud.githubusercontent.com/assets/330324/23533242/c02e9c86-ffb0-11e6-95a7-6b6e30de4a03.png)

![screen shot 2017-03-03 at 01 19 29](https://cloud.githubusercontent.com/assets/330324/23533246/c3920a8e-ffb0-11e6-990d-83aa29f58408.png)

![screen shot 2017-03-03 at 01 19 56](https://cloud.githubusercontent.com/assets/330324/23533251/c73e17f4-ffb0-11e6-8c36-0efbdbbe1746.png)

**Comment by couci** [comment]
thanks @MichaelKohler 
I like the red-pink one and the blue one

**Comment by Ryuno-Ki** [comment]
What does the [contrast ratio](https://leaverou.github.io/contrast-ratio/) tell about the options?

IMHO the most colour options look quite bright. Purple, pink and red ones don't hurt my eyes immediately. @elioqoshi has a better sense for those questions.

**Comment by MichaelKohler** [comment]
Putting this back in the "selected backlog", as this will be influenced by the official styleguide and is not a P1 for now.

**Comment by couci** [comment]
@elioqoshi what do you think in here?

**Comment by elioqoshi** [comment]
let's use Blue 2 like in the new logo we did at All Hands

**Comment by couci** [comment]
I agree @MichaelKohler can you make the changes?

**Comment by MichaelKohler** [comment]
Yes, will come up with a suggestion once I have finished the impact form stuff. This will also include other suggestions Elio had in terms of fonts etc.

**Comment by MichaelKohler** [comment]
(I'll create a new issue for the implementation)
