### ISSUE TITLE
Images for activity pages

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#19]
The area lead in pages have images, and I think the activity pages themselves could benefit from having small images too to compliment the text.

**Comment by brianking** [comment]
Part of push to make site more visually appealing.

Consider screenshots, videos, ....

**Comment by brianking** [comment]
@comzeradd thoughts here on how to best mark up these pages and add visuals?

**Comment by nukeador** [comment]
Note: I've been avoiding html markup to have clean content pages that can be updated by non-technical people. Check a trick I've been using to apply some css classes ;-)

**Comment by MichaelKohler** [comment]
We are currently evaluating requirements here: https://docs.google.com/document/d/1dGKPar5xb5rFveBPxAs5UiSQRCxmeNqnQaMshJnUE7Y/edit

Closing this issue for now.
