### ISSUE TITLE
Create initiatives and activities on the Reps portal

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#2]
We need to define final titles for Initiatives and activities.

**Comment by nukeador** [comment]
@brianking for the initial initiatives are we ok with:

* Developer Engagement
* Rust and Servo
* Test pilot

Or we want other wording like:

* Empower developer communities
* Support the future Mozilla's engine
* Test pilot new features

**Comment by brianking** [comment]
They have to stand out, so I suggest we preface everything with 'Initiatives' or 'Activate' or similar.

e.g.

'Activate - Test Pilot'

Then it matter less the rest of the wording, and we can keep it short.

**Comment by nukeador** [comment]
@akatsoulas Do you need any problems me creating this? We plan to have them by tomorrow.

**Comment by nukeador** [comment]
@brianking can I have the final name for the activities and initiatives to add them to the portal?

**Comment by brianking** [comment]
So we will launch with 3 avtivities:

1. Rust Hack And Learn
2. Web Compatibility Sprint
3. Test Pilot Install

I'm open to new names for 3. Also, let me know the url structure you will be using before setting up the pages.

**Comment by nukeador** [comment]
I've added the initiative and activities to the portal:

https://reps.mozilla.org/reports/new/

We need to see if we have the right matching contribution area that people can easy select there.

**Comment by ioana-chiorean** [comment]
> I've added the initiative and activities to the portal:
Please consider to announce all parties of the change ( we need a clean there also)

**Comment by nukeador** [comment]
> Please consider to announce all parties of the change ( we need a clean there also)

Yeah, that's covered in #11 :-)

**Comment by nukeador** [comment]
Developer Engagement and Firefox Desktop will be functional areas.

**Comment by brianking** [comment]
To summarise, we have 3 activities added to the Reps portal reporting tool.

MozActivate - Dive Into Rust
MozActivate - Web Compatibility Sprint
MozActivate - Test Pilot Install

The first two support Developer Engagement, and the 3rd Firefox Desktop.
