### ISSUE TITLE
Add KPI information on the site

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#20]
We need to add in goals and KPI information in a few places.

- [x] Homepage
- [x] Activity pages
- [x] FAQ

**Comment by brianking** [comment]
Update:

Homepage - we just added a sentence here on what the campaign is about.
"A campaign for Mozillians around the world to have impact in areas key to Mozilla’s mission."

Activity pages - they have been added in the 'Goals for this area' section

TODO
FAQ - will add an entry outlining the top-line goals for the campaign. I need to make a pass first at the numbers to ensure they add up.

Sounds OK @geroter ?

**Comment by geroter** [comment]
Fantastic!!

**Comment by deimidis** [comment]
@brianking thanks, this is really useful information. Are those numbers for each activity or in total? I was looking at Webcompat one, so for example number of add-on installed is the number for the whole time we run the activity, right?

**Comment by brianking** [comment]
@deimidis each activity. We're putting the overall goals as an FAQ entry.

Here is what I have written for the entry. Please review and @geroter as well...

## What are the goals of the campaign?

The primary goal of the campaign is to launch activities that bring value everyone participating, from community mobilizers, to event attendees, to teams at Mozilla.

We have set ourselves targets for Q3 (July-September), 2016. While they are not arbitrary numbers, they are meant to be aspirational and not exact. Whether we come in under target or way over, we will evaluate and iterate for future campaign.

* 6 activities are launched
* 400 people mobilized (Event organisers, ...)
* 3500 unique contributions to the campaign (People attending events, installing add-ons, ...)
* 2000 social shares of campaign activities

These are listed here for transparency, and you can also see our per-activity goals listed under the 'Goals for this area' section on each activity page.

**Comment by geroter** [comment]
Look good!

On 400 people mobilized -- can we make a distinction here between event organizers/initiators and Mozilla volunteers ... and let's make sure people don't confuse this with attendees.

**Comment by brianking** [comment]
FAQ entry added:
https://activate.mozilla.community/faq#what-are-the-goals-of-the-campaign
