### ISSUE TITLE
Focussing carousel breaks it

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/activate.mozilla.community#208]
While working on #180 I noticed, that when focussing the carousel at the bottom, it stops.

Move to it via <kbd>Tab</kbd> to see yourself. The link inside it should get `tabindex="-1"` attribute to disable their focus ability.

But you [should not use a carousel](http://shouldiuseacarousel.com/) for this kind of content anyway :)

**Comment by MichaelKohler** [comment]
I have 4 points tabbing to when I use tab:

* Location bar (Firefox)
* The thing left to it (identity menu) (Firefox)
* Top of the page (not sure what exactly there as I don't have an indicator)
* Something on the bottom of the page (not sure what exactly there as I don't have an indicator)

Is this a general issue or do I lack a certain pref to make it tab-able in general? If it's a general issue, we might want to look into a11y as well. Andre, could you please tell me how to reproduce this?

**Comment by Ryuno-Ki** [comment]
When you have tab focus on an activity card and continue to hit <kbd>Tab</kbd> you will reach a point where you focus the links in the carousel. Firefox/the widget then tries to put the carousel item into viewport and leaves the widget into a state with broken offset.
![broken-carousel](https://cloud.githubusercontent.com/assets/3097194/24840622/804fda2a-1d70-11e7-9532-184faad6a38a.png)

Continuation of tabbing shifts focus to links in the footer area.

**Comment by MichaelKohler** [comment]
I'm closing this as I'm working on a prototype for the future (needs then to be discussed with the Community Development Team of course).
