### ISSUE TITLE
Tech Speaker Activity is Live 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/activate.mozilla.community#209]
- [x] Tech Speaker [wiki](https://wiki.mozilla.org/TechSpeakers#Overview) is updated (Michael Ellis) 
- [x] Form top collect attendee data is ready to go (@couci + @lucyeoh) (dependent on #210)
- [x] Link is updated in [Tech Speaker Activity content](https://docs.google.com/document/d/1It5MxYYOf_B8n1KqUNGHW8c08eCy2NDcGPR76w9N6p4/edit#) (@lucyeoh) 
- [x] Activity goes goes live ( @AlexLakatos )

**Comment by couci** [comment]
https://wiki.mozilla.org/TechSpeakers#Mozilla_Tech_Speakers Wiki page updated

**Comment by couci** [comment]
Feedback form has been created: mzl.la/howwasit

**Comment by couci** [comment]
The activity is ready to go live: https://docs.google.com/document/d/1It5MxYYOf_B8n1KqUNGHW8c08eCy2NDcGPR76w9N6p4/edit# @AlexLakatos @MichaelKohler can we get a timeline on when we can have this live?

**Comment by MichaelKohler** [comment]
Assigning this to me, should be able to do this until April 19th latest. Could you also provide a small picture we can use once the nicer activity detail view is live?

@AlexLakatos do you think we can merge the view before that? Otherwise I'd do it in the master branch as well as in your branch.

**Comment by couci** [comment]
![ts-01](https://cloud.githubusercontent.com/assets/7702955/24954730/35bc60a8-1f89-11e7-9ca2-8e206ff37c72.png)
![ts-02](https://cloud.githubusercontent.com/assets/7702955/24954731/35c15a4a-1f89-11e7-8b6d-3925ac851e19.png)
Small pictures provided

**Comment by MichaelKohler** [comment]
I'll do this on top of Laka's changes for the activity detail view as this will be merged soon. Otherwise we will do work double.

**Comment by MichaelKohler** [comment]
@couci activity is live, do you want to do some kind of announcement?
