### ISSUE TITLE
Get Attendee Data into Bitergia 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/activate.mozilla.community#210]
- [x] Decide on how we'll try and collect attendee data (form, meetup, facebook etc.) (@couci @lucyeoh)
- [x] Create form/mechanism (@couci) 
- [x] Confirm all of the inputs (@lucyeoh)
- [x] Add to Tech Speakers Activity (@couci) 
- [x] Add to all Activate Activities (@couci)
- [ ] Do training call with all Reps on how and why it's important to use the collection mechanism (@couci + @lucyeoh) 
- [ ] Send recording/email out to all Reps

**Comment by couci** [comment]
Activate feedback form here: mzl.la/howwasit @MichaelKohler @AlexLakatos can we add it on every activate page once we launch the new pages?

**Comment by MichaelKohler** [comment]
Sure, do you want to come up with a nice sentence around it? Do we want to do it in its own section?

**Comment by couci** [comment]
Let's use something like: "Gather cool feedback for your activity using the feedback form" @LucyeoH we don't have goals around the feedback form on individual activities on numbers, should we put the same goal with TS?

**Comment by LucyeoH** [comment]
I'm not sure if "cool feedback" is a sentence that will resonate with many people :P. 
But more importantly I think this is the number one way we'll know if an activate activity someone throws is successful. 

It answers the questions "Did any new technical contributors get involved with Mozilla as a result of your event" and we need to find a way to make this super prominent for everyone. 

Here's the line we used in the Tech Speaker activity: 

"Immediately after the event don’t forget to share the link to the feedback form with your attendees: 
**mzl.la/howwasit** (but this is big and bold) 
Remember this is how you’ll know who attended your event, and if you successfully inspired them to action! We recommend adding it to your final slide AND emailing it out after the event."

What about something like that?

**Comment by MichaelKohler** [comment]
On that note, the form mzl.la/howwasit gives me "You need permission". We need to make sure to open that up before we publish this.

**Comment by couci** [comment]
@LucyeoH that seems good to me. In order to "force" the use I am planning to run the training in the reps call and also email key stakeholders on activate.
@MichaelKohler I've opened the survey please check. Could we incorporate it in the activate page?

**Comment by MichaelKohler** [comment]
Yes, the form works now. I'll use Lucy's paragraph for all activities.

**Comment by MichaelKohler** [comment]
PR added here: https://github.com/mozilla/activate.mozilla.community/pull/220

This can only be merged once the activity detail PR is merged (will be very soon).

![screen shot 2017-04-13 at 18 57 19](https://cloud.githubusercontent.com/assets/330324/25015271/66904792-207b-11e7-9ba9-a12b4da424f6.png)

**Comment by MichaelKohler** [comment]
Sorry, this is live now. Should not have closed, since there are further steps to be taken by @couci .

**Comment by couci** [comment]
we are blocked due to this: https://github.com/mozilla/participation-metrics-org/issues/115

**Comment by ranjithrajv** [comment]
Any update on this?

**Comment by MichaelKohler** [comment]
@LucyeoH @couci is this still required? Or will we focus mainly on campaigns and therefore already have Splash to cover this?

**Comment by LucyeoH** [comment]
I'd pause on this. We might come back to it in Q4.


Lucy

**Comment by MichaelKohler** [comment]
Closing for now.
