### ISSUE TITLE
Add Icons to Visualize Impact Numbers (Operation Make Activate Activities Easier To Read)

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/activate.mozilla.community#211]
Add the green bars (visual representations of #s for impact - mimicking the skill section of the VR activitity). 
https://mozillacampusclubs.github.io/Build-a-Virtual-World/

i.e.

Attendees: 
200

Blog Posts
xx

**Comment by MichaelKohler** [comment]
This will be done after https://github.com/mozilla/activate.mozilla.community/pull/205 is merged (as this is an improvement of that)

**Comment by couci** [comment]
#205 has been merged, can we continue with this one?

**Comment by couci** [comment]
@AlexLakatos @MichaelKohler status update here?

**Comment by couci** [comment]
@AlexLakatos please update here otherwise we need to put this on blocked

**Comment by MichaelKohler** [comment]
We are currently working on a refresh of the Activate page. This project is in its early stages, but we will have a look at this as we're rewriting the full website.
