### ISSUE TITLE
Create a TS map available for Reps in the activate site

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#213]
- [x] Create bug for key @couci
- [x] Enter bug on parsys github tracking repo @couci, @LucyeoH 
- [ ] Create the map @AlexLakatos 
- [ ] Add it in the activate page @AlexLakatos @MichaelKohler

**Comment by mermi** [comment]
This Map[1] contains all the Tech Speakers still some of them missing but it could be helpful for this issue :D
[1] https://mte90.github.io/Tech-Speakers-Map/

**Comment by couci** [comment]
Bug has been created and api requested. Next step is to add as a user story in partsys repo

**Comment by couci** [comment]
@AlexLakatos how are we doing with this one?

**Comment by couci** [comment]
@AlexLakatos is this still relevant?

**Comment by MichaelKohler** [comment]
@couci @LucyeoH I suppose this is not relevant anymore, can we close it?
