### ISSUE TITLE
Rework on content for WebVR and Rust

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#214]
- [ ] have a meetings with functional areas @couci @LucyeoH 
- [ ] rework on drafts @couci

**Comment by LucyeoH** [comment]
@couci how is this different than #214 

Also I think you and Christos should have a unified approach to working with these teams. The output you want is closely related enough and it's less people coming at them from our team with requests.

**Comment by MichaelKohler** [comment]
Lucy, this is 214 ;)

**Comment by MichaelKohler** [comment]
Yes, this seems like a dupe of #215. @couci please close one of these as they are the same :)

**Comment by couci** [comment]
yes I got too excited apparently, closing this on
