### ISSUE TITLE
Rework on content for WebVR and Rust

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#215]
- [x] @couci meet with @bacharakis to create unified strategy
- [ ] create drafts @couci 
- [ ] publish in the website @MichaelKohler @AlexLakatos

**Comment by LucyeoH** [comment]
@couci I'd recommend working closely with Christos on this. He's already working with Rust to create an activity for them using a contractor and adapting that for activate will probably be easier than requesting a separate activity (which they don't have time to build for us).

**Comment by couci** [comment]
Meeting with @bacharakis has taken place, rework on WebVR has started, we will finish it on Thursday

**Comment by couci** [comment]
WebVR is still on early stages and we decided to base the new Rust activities based on the Rust campaign in India happening on June

**Comment by couci** [comment]
RainofRust learnings will be incorporated in July. WebVR is still on early stages
