### ISSUE TITLE
Put the great Event Planning guide online

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#217]
- [x] The link is online on the activate site @couci @MichaelKohler 
- [ ] Current activities are been reworked to take out a lot of text @couci

**Comment by couci** [comment]
Here is the link for the Event Planning guide @MichaelKohler can we put it online before FAQ?

**Comment by MichaelKohler** [comment]
This also needs to be linked to instead of the repeating "setup your event" things in the activities, right?

**Comment by couci** [comment]
Yes I am working on what to put out from the current activities as we speak :)

**Comment by MichaelKohler** [comment]
Do you have some text or should I start with the PR and come up with a suggestion?

**Comment by couci** [comment]
So now lets put it on the tab and as we go we change the wording on activities

**Comment by MichaelKohler** [comment]
The guide is online. Once you have the changes coming out of that for the existing activities, please tell me :)

**Comment by MichaelKohler** [comment]
@couci should we replace all the event setup texts in the existing activities with a link to the guide now?

**Comment by couci** [comment]
Yes let's not wait any longer. Do you need help with that (on what part to take out) or is it easy?

**Comment by MichaelKohler** [comment]
Should be easy enough.

**Comment by MichaelKohler** [comment]
PR: https://github.com/mozilla/activate.mozilla.community/pull/243
