### ISSUE TITLE
Correct identification of the language Brazilian Portuguese

### ISSUE THREAD

**Issue by barrosgeraldo** [mozilla/activate.mozilla.community#229]
Our language is derived from Portuguese from Portugal, but our Portuguese is Brazilian, so the correct one is use PT-BR. It is not good practice to use PT for Brazilian Portuguese, because our community in Portugal may want to translate this project in the future and they will want to use PT in the "lang".

See more: https://github.com/mozilla/activate.mozilla.community/pull/227

**Comment by MichaelKohler** [comment]
Pull request opened: https://github.com/mozilla/activate.mozilla.community/pull/232

@barrosgeraldo please note that this PR once merged will break a lot of changes on your side as I've renamed folders etc

**Comment by barrosgeraldo** [comment]
@MichaelKohler, ok, tks.
