### ISSUE TITLE
Frequently Asked Questions - Update

### ISSUE THREAD

**Issue by barrosgeraldo** [mozilla/activate.mozilla.community#230]
Please, update the answer for the this question: "What are the goals of the campaign?".

Thanks.

**Comment by MichaelKohler** [comment]
Oh yes, totally! @couci could you please provide a text here? :)

**Comment by couci** [comment]
Sorry for the late reply.
I will quote what we have on our launch page for that:
The goal is providing guidance to mobilizers on how to recruit contributors and create community around meaningful Mozilla projects.

**Comment by couci** [comment]
@MichaelKohler are we good to go with the above comment?

**Comment by MichaelKohler** [comment]
Makes sense yeah. Will integrate that.

**Comment by MichaelKohler** [comment]
PR opened here https://github.com/mozilla/activate.mozilla.community/pull/242
