### ISSUE TITLE
Share feedback link is not working!

### ISSUE THREAD

**Issue by hossainalikram** [mozilla/activate.mozilla.community#233]
I was looking over https://activate.mozilla.community/techspeakers/ and when i tried to click on Share feedback option in "Goals for this Activity", I am seeing an 404 error. So, thought of creating an issue :)

The link is now set to - https://activate.mozilla.community/techspeakers/mzl.la/howwasit

Should be ( I am guessing) - http://mzl.la/howwasit

**Comment by MichaelKohler** [comment]
Oooh, will fix ASAP. Should be done in max 6 hours. Thanks for the report.

**Comment by hossainalikram** [comment]
Is the correct link this one http://mzl.la/howwasit ?

**Comment by MichaelKohler** [comment]
Yes!

**Comment by MichaelKohler** [comment]
(as the link in the main section further down is)

**Comment by hossainalikram** [comment]
I did a pull request, giving the link to work.

**Comment by MichaelKohler** [comment]
PR merged, thank you!
