### ISSUE TITLE
Dive Into Rust | Under Event Flow Rust downloads link is redirecting to install page rather than other-installers page

### ISSUE THREAD

**Issue by shahbaz17** [mozilla/activate.mozilla.community#240]
**Steps to reproduce**

Visit https://activate.mozilla.community/rust-hack/
Under Event Flow
  -install rust , click on Rust downloads ( alternative )

**What happened? (actual result)**
It takes us to https://www.rust-lang.org/downloads.html which redirects to https://www.rust-lang.org/en-US/install.html which is essentially the same content which is just above this link ( i.e rustup )

**What should have happened? (expected results)**
It should take us to https://www.rust-lang.org/en-US/other-installers.html

**Comment by MichaelKohler** [comment]
PR merged, thank you!
