### ISSUE TITLE
Impact form dashboard - Type of events

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#247]
As a Reps community manager I want to see the statistics on the types of events that have submitted the impact form

**Comment by MichaelKohler** [comment]
We gather the type of the event as a free text field. People are writing anything in there. Do you still want a unique list of all values submitted?

**Comment by couci** [comment]
Yes, let's filter that based on the first question "what kind of event is this" that has only specific pre-filled answers

**Comment by MichaelKohler** [comment]
OK, will do.

**Comment by MichaelKohler** [comment]
PR created here: https://github.com/mozilla/activate.mozilla.community/pull/292
