### ISSUE TITLE
New impact form page

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/activate.mozilla.community#249]
Create a translatable impact form page & have a clear documentation so Rep can localize it in their own language.

**Comment by MichaelKohler** [comment]
I think I'll have some time this weekend to look into possible ways for this.

**Comment by kelimuttu** [comment]
Thanks, Michael. I'm working on it right now. Let's hope the PR would be ready by then so you can review it this weekend.

**Comment by MichaelKohler** [comment]
Ah, that's great :) thanks

**Comment by Mte90** [comment]
I don't know if google forms is the best way but as I suggested on discourse we can evaluate an open source software for forms like limesurvey that support multilanguage forms.

**Comment by kelimuttu** [comment]
@Mte90 we should really consider that in the future. Right now, we don't have enough technical support to use other services. That's why we use this trick. 

@MichaelKohler I guess we can close this since the PR has been merged.
