### ISSUE TITLE
Romanian (Ro) localization

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/activate.mozilla.community#25]
Hey,
Here to help and localize it in Romanian. 

Thanks!

https://github.com/ioana-chiorean/activate.mozilla.community/tree/gh-pages/_data/l10n
https://github.com/ioana-chiorean/activate.mozilla.community/blob/gh-pages/_data/l10n/ro.yml

the rest to come:
- https://github.com/ioana-chiorean/activate.mozilla.community/tree/gh-pages/_pages

**Comment by deimidis** [comment]
Hi, I didn't see this issue before sending my pull request adding pt and fr. I need that someone review my changes so we are sure we didn't make any mistakes. In the meantime, you could see that I added a lang folder inside _pages so you culd duplicate it and made modifications to make it work for Romanian

**Comment by brianking** [comment]
Given the discussion in #34, let's put a HOLD on integrating any more locales for now.

**Comment by ioana-chiorean** [comment]
o.k. ......

**Comment by MichaelKohler** [comment]
Sorry it took so long. After all this time, we now decided to go back to the old system so we don't block on any translations anymore. This means that the translations live in the GitHub repository here. You can get more information on how to localize in the README.

General flow:

* Fork this project
* Look at the following folders:
https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_pages/
https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_data/l10n/
https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_includes/
* If there is no subfolder for your locale, create one
* Copy the English files to the subfolder of your locale and start translating them, please note that strings can be in any of the above mentioned folders.
* Create a PR with your changes.
* We will then add the language to the language dropdown

Feel free to ping me for any questions you might have.

**Comment by MichaelKohler** [comment]
We are currently working on a refresh of the Activate page. This project is in its early stages, but what I can say now is that localization improvements (Pontoon) will be a big part of it. I'm closing this as it will be considered in the refresh. Once we will talk about about what locales to enable to be translated we will revisit all localization issues in this repository, so there is no need to create a new request somewhere.
