### ISSUE TITLE
Publish Nightly activity

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#268]
As the Nightly activity is feature-complete in terms of content, I've started a branch (https://github.com/MichaelKohler/activate.mozilla.community/tree/feature/nightly_activity) to add it to the page. Here are some screenshots:

![screen shot 2017-06-22 at 00 24 41-fullpage](https://user-images.githubusercontent.com/330324/27409717-38114aee-56e3-11e7-81cd-3e083b567732.png)

![screen shot 2017-06-22 at 00 30 27-fullpage](https://user-images.githubusercontent.com/330324/27409722-3dae4448-56e3-11e7-8cce-8b19e80a10a7.png)

Next steps:
* Get text for Discourse announcement (so we can put the link into the activity)
* Get quick review on the page according to the screenshots above
* Send PR

Any thoughts?

**Comment by caitmuenster** [comment]
Oh, this is such a good Activate campaign! Can I ask who's taking point on this? I'd love to share this with some of the QA leads.

**Comment by MichaelKohler** [comment]
> Oh, this is such a good Activate campaign! Can I ask who's taking point on this? I'd love to share this with some of the QA leads.

Main contact for this activity on staff side (functional area) is Marcia. Konstantina for the Activate campaign itself (program).

**Comment by caitmuenster** [comment]
Awesome - thanks @MichaelKohler!

**Comment by MichaelKohler** [comment]
PR created here: https://github.com/mozilla/activate.mozilla.community/pull/270

**Comment by MichaelKohler** [comment]
https://activate.mozilla.community/nightly/ yay!!
