### ISSUE TITLE
Impact form localization (BD-BN)

### ISSUE THREAD

**Issue by atiqueahmedziad** [mozilla/activate.mozilla.community#269]

**Comment by couci** [comment]
@atiqueahmedziad what s the status update here?

**Comment by MichaelKohler** [comment]
We are currently working on a refresh of the Activate page. This project is in its early stages, but what I can say now is that localization improvements (Pontoon) will be a big part of it. I'm closing this as it will be considered in the refresh. Once we will talk about about what locales to enable to be translated we will revisit all localization issues in this repository, so there is no need to create a new request somewhere.
