### ISSUE TITLE
Expired HTTPS certificate on activate.mozilla.community

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/activate.mozilla.community#272]
The certificate on https://activate.mozilla.community/ has expired 20 minutes ago.

**Comment by MichaelKohler** [comment]
Thanks for the report. I've redirected this to the ParSys team to take care of.

**Comment by flamingspaz** [comment]
https://github.com/mozilla/parsys/issues/187

**Comment by MichaelKohler** [comment]
Thanks @flamingspaz , this is fixed. And thanks @MikkCZ for reporting!
