### ISSUE TITLE
Move API to Community IT

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#274]
- [x] Initial docker image
- [x] Remove credentials from docker image and write tutorial on how to create new credentials to be used with another google account (to be defined which one)
- [x] Deploy initial docker image without credentials to docker hub through Travis CI
- [x] Create bug for ParSys

**Comment by MichaelKohler** [comment]
Current status and next steps:
- [x] Initial docker image
- [ ] Remove credentials from docker image and write tutorial on how to create new credentials to be used with another google account (to be defined which one)
- [ ] Deploy initial docker image without credentials to docker hub through Travis CI
- [ ] Create bug for ParSys

**Comment by MichaelKohler** [comment]
The only thing left is the automatic scheduling of input fetching. I'll be working on this over the coming days.

What we need to figure out is which Google account we can use for the credentials. We need to have an auth token to be able to fetch the responses. Best case scenario would be the reps-council@mozilla.com alias, though I'm not sure if that is possible. Otherwise we probably could create activate@mozilla.com or similar and give that account read permissions on the responses form. @couci what do you think? I'm happy to explain how to run the project initially to get the credentials. This is very similar to https://developers.google.com/sheets/api/quickstart/nodejs which explains the steps that would need to be taken on that account.

**Comment by MichaelKohler** [comment]
ParSys bug filed for now. This means after reviewing the open PR, we need to figure out the credentials part mentioned above. Then this should be ready.

https://bugzilla.mozilla.org/show_bug.cgi?id=1386256

**Comment by couci** [comment]
can I ask why the council alias or even the review team alias are not possible?

**Comment by MichaelKohler** [comment]
I'm not sure if an alias can request those credentials. Is there even a log in for the alias?

**Comment by couci** [comment]
in that case we need to share the login info among the council members in order to be able to see the info, otherwise we exclude the info to one person and thus we can directly add a personal emal (for example Ruben's or mine).

**Comment by MichaelKohler** [comment]
> in that case we need to share the login info among the council members in order to be able to see the info, otherwise we exclude the info to one person and thus we can directly add a personal emal (for example Ruben's or mine).

No, this is only for the access of the backend, so we can display it on the website. The responses form just needs to be shared with that account as well. The council members still have access to the doc as normal.

**Comment by couci** [comment]
ok then I can request an email account on activate@mozilla.com

**Comment by couci** [comment]
ok then I can request an email account on activate@mozilla.com

**Comment by couci** [comment]
Request added, waiting for a reply

**Comment by couci** [comment]
Alias obtained, let me know what are the next steps.

**Comment by MichaelKohler** [comment]
> Alias obtained, let me know what are the next steps.

Let's move this to DM so I can explain you how to get the credentials without me seeing them.

**Comment by MichaelKohler** [comment]
This is not necessary anymore, I've published the non-confidential part in the spreadsheet and am reading from there now.

**Comment by MichaelKohler** [comment]
Eh, sorry. Shouldn't have closed it. So, we still need the deployment and the the followup with ParSys.

**Comment by MichaelKohler** [comment]
Docker Hub image: https://hub.docker.com/r/michaelkohler/activate.mozilla.community/

ParSys bug updated: https://bugzilla.mozilla.org/show_bug.cgi?id=1386256

Once the image is hosted we can change the code to reference that domain and we can merge this.
