### ISSUE TITLE
Rebuild the Rust activity based on the RainofRust guide

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#275]
The new activity will be based on the activity that the RainofRust team built: https://github.com/MozillaIndia/RustIndia/tree/master/RainOfRust#advance-rust-events

Steps:
- [ ] Create a draft
- [ ] Receive feedback/review
- [ ] Get doc ready to be uploaded

**Comment by barrosgeraldo** [comment]
Hi @couci,

At Brazil we're using this [workshop flow](https://geraldobarros.me/setting-up-the-success-of-dive-into-rust-workshops-at-sao-paulo/).

**Workshop Flow**

    Welcome, agenda and offline icebreakers. 10m
    Rust and the Future of Systems Programming’s movie. 6m
    Introducing Rust: What is it? Benefits? Use in the real world. 15m
    Introducing language using the Rust Book V2. 15m
    Introducing rustup, Cargo, crates.io, rustdoc, playground and quickly activities to test the Rust install and become familiar with Rust. 15m
    Exercises with the Exercism, an exercise together and in a group. 30m
    Introducing to the Ownership and exercise: move semantics of Rustlings. 30m
    Structs and enums exercises. 30m
    Exercise about parallelism: A parallel bitcoin miner. 30m
    Free Rust Hackathon —  attendees will choose and develop a project with Rust. 100m
        Continue Exercising Exercism
        Client and chat server for terminal
        Web client (API access or scraping)
        Web server with JSON API
        Access a database
        Make a graphical interface
        Use a Rust library through your favorite language (Python)
        Rust-python binding
            Creating a python module in Rust which focusses on delivering high performance
            Code
            Read the documentation here
    Open feedback e feedback for Mozilla using https://mzl.la/howwasit. 5m

**Comment by leodasvacas** [comment]
I made the flow used in Brazil, I can help out with a new flow for the activity.

**Comment by MichaelKohler** [comment]
Superseded by https://github.com/mozilla/activate.mozilla.community/pull/293
