### ISSUE TITLE
Servo and Privacy invisible

### ISSUE THREAD

**Issue by mijanurrahman** [mozilla/activate.mozilla.community#28]
Servo and Privacy icon are greyed in Firefox browser. But it looks visible in other browser (ex: Chrome)

**Comment by MichaelKohler** [comment]
In my opinion they should be greyed out since they're not launched yet. Let me see why they are not greyed out in Chrome.

**Comment by ioana-chiorean** [comment]
Damn it.. indeed. 
![screenshot from 2016-08-12 18-05-21](https://cloud.githubusercontent.com/assets/1391451/17626815/93fe9e56-60b7-11e6-9b1d-fee597bbe6e8.png)

**Comment by MichaelKohler** [comment]
This seems to be because of

```
.home .disabled {
    filter: grayscale(90%) opacity(25%);
    font-weight: normal;
}.home .disabled {
    filter: grayscale(90%) opacity(25%);
    font-weight: normal;
}
```

which does not work in Chrome. I'll file a PR right away.

**Comment by brianking** [comment]
Thank you @MichaelKohler for the fix!

Yes indeed it is intentional for these not to be active until we launch activities in these categories.
