### ISSUE TITLE
Implement new branding

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#283]
Since https://github.com/mozilla/activate.mozilla.community/issues/140 is done, we need to implement the new branding accordingly. I've started doing this, however, please note, I'm neither a designer, UI designer, nor a UX designer. I went with my gut feeling, trying to keep the (publicly) known guidelines in mind.

I know that there are still some rough edges (navigation for example), but I currently do not have good ideas on how to better do it. That's why I need feedback ;) If there is a good collaborative platform where you can do comments, I'm happy to upload the screenshots there to make it easier.

Timeline:
- [ ] Initial feedback gathered and issues addressed (@MichaelKohler, Due: August 22nd)
- [ ] Code is updated and Pull Request is created (@MichaelKohler, Due: August 24th)
- [ ] PR is reviewed and merged (-> Website is live) (@MichaelKohler, Due: August 30th)

Here is what I currently have. Every feedback is welcome! /cc @elioqoshi, please provide feedback regarding official guidelines as well

# DESKTOP
![screen shot 2017-08-14 at 20 21 31-fullpage](https://user-images.githubusercontent.com/330324/29285316-716fa72a-812e-11e7-964c-6a40e44170ae.png)

![screen shot 2017-08-14 at 20 22 16-fullpage](https://user-images.githubusercontent.com/330324/29285318-7171cd70-812e-11e7-9b62-0449322d1219.png)

![screen shot 2017-08-14 at 20 22 24-fullpage](https://user-images.githubusercontent.com/330324/29285320-7174f612-812e-11e7-9b36-1f09ecfc504b.png)

![screen shot 2017-08-14 at 20 22 29-fullpage](https://user-images.githubusercontent.com/330324/29285321-71783cb4-812e-11e7-81e6-a9cffbd87948.png)

![screen shot 2017-08-14 at 20 22 33-fullpage](https://user-images.githubusercontent.com/330324/29285317-717026fa-812e-11e7-8f96-fd271b3c1454.png)

![screen shot 2017-08-14 at 20 22 38-fullpage](https://user-images.githubusercontent.com/330324/29285319-71729a84-812e-11e7-9d65-e366ed573a5f.png)

![screen shot 2017-08-14 at 20 22 45-fullpage](https://user-images.githubusercontent.com/330324/29285324-71a99368-812e-11e7-9844-c0efb685d54a.png)

![screen shot 2017-08-14 at 20 22 51-fullpage](https://user-images.githubusercontent.com/330324/29285325-71adebde-812e-11e7-89bf-efd36f25acdc.png)

Hovered menu state:
![screen shot 2017-08-14 at 20 23 06](https://user-images.githubusercontent.com/330324/29285332-7bbe97ae-812e-11e7-84b8-f006fff363e5.png)

# MOBILE

![screen shot 2017-08-14 at 20 28 02-fullpage](https://user-images.githubusercontent.com/330324/29285581-3a1bd9a0-812f-11e7-824c-709031fb9514.png)

![screen shot 2017-08-14 at 20 28 29-fullpage](https://user-images.githubusercontent.com/330324/29285579-3a188df4-812f-11e7-8427-eb7ac8925f03.png)

![screen shot 2017-08-14 at 20 28 36-fullpage](https://user-images.githubusercontent.com/330324/29285583-3a1cb424-812f-11e7-9307-b2b18074c862.png)

![screen shot 2017-08-14 at 20 28 42-fullpage](https://user-images.githubusercontent.com/330324/29285584-3a1d9b6e-812f-11e7-9f0b-d1da34fdb42e.png)

![screen shot 2017-08-14 at 20 28 46-fullpage](https://user-images.githubusercontent.com/330324/29285582-3a1c30e4-812f-11e7-807f-a746f3095258.png)

![screen shot 2017-08-14 at 20 28 50-fullpage](https://user-images.githubusercontent.com/330324/29285580-3a1b604c-812f-11e7-8c40-c975d92e6769.png)

![screen shot 2017-08-14 at 20 28 54-fullpage](https://user-images.githubusercontent.com/330324/29285586-3a4dd1f8-812f-11e7-96c3-ef483bfea3f1.png)

![screen shot 2017-08-14 at 20 29 01-fullpage](https://user-images.githubusercontent.com/330324/29285585-3a49b244-812f-11e7-8824-62a2c3be704f.png)

"Clicked" menu state:
![screen shot 2017-08-14 at 20 26 15](https://user-images.githubusercontent.com/330324/29285500-fe7deff0-812e-11e7-96ca-04e410c4c334.png)

**Comment by elioqoshi** [comment]
@MichaelKohler Thanks for the hard work and sorry for the delay in getting back to this.

Let me start off with a few easy blockers which can be changed:

- The Logo might be more suitable if it's completely horizontal. I will provide you with a file for that.
- In the paragraphs and headers I see some inconsistency between Fira, Zilla, and even Arial (I think). I'd suggest h1 and h2 use Zilla Regular Highlight and h3-h6 use Zilla Regular. Fira Sans for paragraphs. What do you think?
- We should use the new Nightly logo I suppose.
- In the home page, the various projects have their paragraphs left aligned but the heading titles center aligned. Let's make the titles left aligned as well.

-Generally, having the home page header look more in the style of mozillafestival.org could give us some more consistency with other Mozilla sites

**Comment by elioqoshi** [comment]
I'd also add the Participation Guidelines to the Footer. See how MozFest did it:
https://mozillafestival.org/

**Comment by elioqoshi** [comment]
![1](https://user-images.githubusercontent.com/5436686/29604487-efebe9e6-87e7-11e7-9151-3366e8529635.png)

Quick Mockup of how the Header on the Main Page could look like.

**Comment by MichaelKohler** [comment]
Thanks Elio.

1) The blockers are quite easy to fix, will do that tonight or tomorrow
2) Mockup looks good to me, will do that as well :)

**Comment by elioqoshi** [comment]
Updated Mockup

![2](https://user-images.githubusercontent.com/5436686/29604735-c210996c-87e8-11e7-8578-dedac8204094.png)

Also, can we try doing the categories (TESTING, PROGRAMMING etc.) in Zilla Bold with "HOURS" being in Regular. Would be great to use the new color palette as well.

**Comment by MichaelKohler** [comment]
> Also, can we try doing the categories (TESTING, PROGRAMMING etc.) in Zilla Bold with "HOURS" being in Regular. Would be great to use the new color palette as well.

Sure, any preferences for the colors?

**Comment by elioqoshi** [comment]
Let's try:

Green 2 for PROGRAMMING
Red 2 for TESTING
Purple 2 for PARTICIPATION

https://mozilla.ninja/visualelements/

**Comment by MichaelKohler** [comment]
Everything done apart from:
* Zilla Regular doesn't seem to work
* Header image / navigation

I will continue tomorrow and then send new screenshots.

**Comment by brianking** [comment]
For me, the black background on text headings is a bit too much, perhaps not on the summary pages, but on the individual listings page for sure. They divert a lot of attention from the content.

**Comment by elioqoshi** [comment]
@brianking It's used on MDN as well so it's already canon. Not sure if we should divert from that.

**Comment by MichaelKohler** [comment]
> Zilla Regular doesn't seem to work

I can't fix this right now, as it only doesn't work in Nightly (left), works in Release (right)..

![screen shot 2017-08-26 at 15 43 41](https://user-images.githubusercontent.com/330324/29741887-9eafaf28-8a75-11e7-84b5-ae21e08bf3a7.png)

**Comment by MichaelKohler** [comment]
> I can't fix this right now, as it only doesn't work in Nightly (left), works in Release (right)..
At least not when using Google Fonts. I've added the fonts to the repo for now. Sorry for the spam ;)

**Comment by MichaelKohler** [comment]
@elioqoshi should the header like your mockup on every page or just on the frontpage? If only on the frontpage, how should it look without background image?

**Comment by elioqoshi** [comment]
@MichaelKohler only front page. On inner pages make it with the blue background color.

**Comment by ranjithrajvasam** [comment]
@MichaelKohler Any update on this issue? would like to know what is the deadline to close it? :)

**Comment by MichaelKohler** [comment]
The only thing left is the implementation of the header as in Elio's mockup above (just for the front page). The rest is done in https://github.com/MichaelKohler/activate.mozilla.community/tree/feature/branding_update?files=1 . I don't have time until the website for the Firefox Quantum Sprint is finished as that has a higher priority.

**Comment by ranjithrajv** [comment]
Any update on this? How can anyone help fix this ASAP.

**Comment by MichaelKohler** [comment]
We are currently working on a refresh of the Activate page. This project is in its early stages, but a branding alignment is part of it.
