### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/activate.mozilla.community#285]
Google has some tips for you:

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Factivate.mozilla.community%2F

https://testmysite.withgoogle.com/intl/en-gb

**Comment by MichaelKohler** [comment]
We are currently working on a refresh of the Activate page. This project is in its early stages, but we will have a look at this as we're rewriting the full website. Thanks!
