### ISSUE TITLE
Reboot the Extensions Activity: content work

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#286]
This is a tracking issue for improving the Extensions activity

Tasks:
- [ ] Rewrite the activity giving a more teaching tone @caitmuenster Due date: 25th of August
- [ ] Getting feedback on the new activity @caitmuenster 
- [x] Contact key volunteers to participate on pilot activity @couci Due date: 18th of August
- [x] Get volunteers approval @couci Due date: 18th of August
- [x] Organize first meeting @couci Due date: 25th of August

**Comment by couci** [comment]
email sent to key volunteers

**Comment by couci** [comment]
Volunteers okays done, first meeting on Wednesday the 23rd

**Comment by caitmuenster** [comment]
Working document can be found here: https://docs.google.com/document/d/1yr7KhtI2vDKD8qjg3wGA7JL3nuVmlUCtOJGwFkxrEoA/edit#heading=h.73tl1jpwl9p1

**Comment by MichaelKohler** [comment]
See https://github.com/mozilla/activate.mozilla.community/pull/294

**Comment by MichaelKohler** [comment]
This has been rebooted.
