### ISSUE TITLE
Localization Request for Malayalam Language (ml)

### ISSUE THREAD

**Issue by riginoommen** [mozilla/activate.mozilla.community#287]

**Comment by MichaelKohler** [comment]
We are currently working on a refresh of the Activate page. This project is in its early stages, but what I can say now is that localization improvements (Pontoon) will be a big part of it. I'm closing this as it will be considered in the refresh. Once we will talk about about what locales to enable to be translated we will revisit all localization issues in this repository, so there is no need to create a new request somewhere.
