### ISSUE TITLE
Create FAQ page

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#3]
We need a FAQ page.

Content TBD

**Comment by nukeador** [comment]
Placeholder ready here https://mozilla.github.io/activate.mozilla.community/faq

Editable from: https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_pages/faq.md

**Comment by nukeador** [comment]
@brianking I added some initial content.

**Comment by brianking** [comment]
I can't think of anything else to add right now, so closing.
