### ISSUE TITLE
Français (Fr) localization

### ISSUE THREAD

**Issue by womozci** [mozilla/activate.mozilla.community#30]

**Comment by deimidis** [comment]
Hi, I just add pull request to add french to this website (besides other changes). If you want to begin before this is approved, you could do it in my branch: https://github.com/deimidis/activate.mozilla.community

**Comment by womozci** [comment]
Great and thank you for your help

**Comment by brianking** [comment]
Given the discussion in #34, let's put a HOLD on integrating any more locales for now.

**Comment by brianking** [comment]
I see fr is live on the site.
As the content is now stable, is there a plan to finish the fr translation?

**Comment by womozci** [comment]
Sorry Brian, Yes plan to finish the  fr translation i hope next week.

**Comment by MichaelKohler** [comment]
Once the translations are all on Pontoon, it will be easier to translate. Will update this issue once this is done.

**Comment by MichaelKohler** [comment]
Sorry it took so long. After all this time, we now decided to go back to the old system so we don't block on any translations anymore. This means that the translations live in the GitHub repository here. You can get more information on how to localize in the README. 

General flow:
* Fork  this project
* Make changes to the following folders/files to translate them: 
https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_pages/fr
https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_data/l10n/fr.yml
https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_includes/fr
* Create a PR with your changes.

**Comment by MichaelKohler** [comment]
We are currently working on a refresh of the Activate page. This project is in its early stages, but what I can say now is that localization improvements (Pontoon) will be a big part of it. I'm closing this as it will be considered in the refresh. Once we will talk about about what locales to enable to be translated we will revisit all localization issues in this repository, so there is no need to create a new request somewhere.
