### ISSUE TITLE
Check of Copy

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#318]
Before we can merge the PR with the rebranding, we need to make sure that the copy is as we want it. Otherwise our localizers will translate stuff we will change again.

Here is the latest state, including rebranding and my on-top fixes: https://rewrite.michaelkohler.info/

@couci please go through it and tell me any wishes regarding copy, including making sure that legal agrees with the newsletter forms. I'd say we need to add the general sentence to all of these.

**Comment by couci** [comment]
approved copy was provided to @MichaelKohler by pm
@MichaelKohler let me know if you need anything else

**Comment by MichaelKohler** [comment]
I've changed the copy. Additionally I've added the legal newsletter text to all instances of the newsletter form -- when no campaign is shown and in the footer.

Check it out here and close this issue if okay: 

https://rewrite.michaelkohler.info/ (without active campaign)
https://rewrite-campaign.michaelkohler.info/ (with active campaign)

**Comment by couci** [comment]
this looks good to me, thanks @MichaelKohler 
Question on the campaign page is there a possibility that we won't have anything on the upcoming part?

on the old one could we add past campaigns? do you need help with adding those old websites?
