### ISSUE TITLE
Event Guide Links

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/activate.mozilla.community#319]
Currently the event guide links are pointing to the Activate Page: https://rewrite.michaelkohler.info/eventguide

This is not nicely styled, so we should decide whether we want to style this site and keep it; or if we want to link to Discourse.

@couci thoughts?

**Comment by couci** [comment]
I think the easiest solution is to move it, however I would like to keep it for consistency. @MichaelKohler how much time will it get you to style it up?

**Comment by MichaelKohler** [comment]
Well, depends on how it should look. Making it look "okay" shouldn't take too much time, but it will be simple.

**Comment by couci** [comment]
Simple is all we need :)

**Comment by MichaelKohler** [comment]
@couci Please check https://rewrite.michaelkohler.info/eventguide and close this if all good.

**Comment by couci** [comment]
this looks good, closing
