### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Mte90** [mozilla/activate.mozilla.community#32]
We want to start to translate it's possible to create the it.yml?
We want manage the translation on https://github.com/MozillaItalia and next ask for a pr here.

**Comment by MichaelKohler** [comment]
I'd suggest to fork the repo to your organisation and then create the file, add it to the language list and translate all the files within the _pages folder. You can take Spanish as a reference if you want.

Does that sound ok to you?

**Comment by Mte90** [comment]
Ok!
Can someone assign to me that ticket?

**Comment by deimidis** [comment]
Hi @Mte90 probably is better if you wait for the pull request I sent. I hope to have that resolve today, and there you will find a lang folder with all the pages ready to translate

**Comment by brianking** [comment]
Given the discussion in #34, let's put a HOLD on integrating any more locales for now.

**Comment by MichaelKohler** [comment]
Sorry it took so long. After all this time, we now decided to go back to the old system so we don't block on any translations anymore. This means that the translations live in the GitHub repository here. You can get more information on how to localize in the README.

General flow:

* Fork this project
* Look at the following folders:
https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_pages/
https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_data/l10n/
https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_includes/
* If there is no subfolder for your locale, create one
* Copy the English files to the subfolder of your locale and start translating them, please note that strings can be in any of the above mentioned folders.
* Create a PR with your changes.
* We will then add the language to the language dropdown

Feel free to ping me for any questions you might have.

**Comment by Mte90** [comment]
In the meantime the project is on pontoon and we are organizing the translation of the content, probably we want to add external resources in italian in the translation

**Comment by MichaelKohler** [comment]
We are currently working on a refresh of the Activate page. This project is in its early stages, but what I can say now is that localization improvements (Pontoon) will be a big part of it. I'm closing this as it will be considered in the refresh. Once we will talk about about what locales to enable to be translated we will revisit all localization issues in this repository, so there is no need to create a new request somewhere.
