### ISSUE TITLE
Add Common Voice activity at the activate website

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#325]
@MichaelKohler we created a new activity to be added on the activities list. You can find the doc here:
https://docs.google.com/document/d/1GtiqmK37dKPykTC2abEHroL5d-Fc5BsTVbTYxGjm0vE/edit?ts=5c8931c6

Let me know if you need any more info

**Comment by MichaelKohler** [comment]
I'll create an initial version, then we can figure out what exactly we're missing ;)

**Comment by MichaelKohler** [comment]
@couci also, are you sure we wanna take the Nightly one? Would it make sense to take the WebVR one and split into foldable sections?

**Comment by MichaelKohler** [comment]
Nevermind, it says in the doc about the sections

**Comment by couci** [comment]
@MichaelKohler what do you think the time estimation will be on this one?

**Comment by MichaelKohler** [comment]
Let's say by the end of Sunday for you to review on Monday. Does that sound good?

**Comment by couci** [comment]
sounds good to me
