### ISSUE TITLE
Pontoon out of sync?

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#336]
Hi,

I don't see the new localization files over pontoon, I just see the old ones here:

https://pontoon.mozilla.org/es/common-voice/

Cheers.

**Comment by MichaelKohler** [comment]
Did you link the wrong project or did you intend to file this issue in the voice-web repo?

For activate it would be https://pontoon.mozilla.org/es/mozilla-activate/

**Comment by nukeador** [comment]
You are right, I got confused.
