### ISSUE TITLE
Add Upcoming Campaigns on the Campaign Site

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/activate.mozilla.community#339]
Can we add an "upcoming" campaigns section to the campaign page of the activate site? I think we even had a mock-up for that at some point (goes searching).

**Comment by MichaelKohler** [comment]
If you have a mockup, sure. So we went from months without campaign to the need to have an active and upcoming campaign? I like that ;)

**Comment by MichaelKohler** [comment]
If you don't have a mockup, feel free to draw something how it approximately should look and we can go from there.

**Comment by LucyeoH** [comment]
Mock-up acquired! The only thing I'd do is add a "subscribe" button to the upcoming events.  
![Activate_Page03_Campaigns_PlusUpcoming](https://user-images.githubusercontent.com/8070833/55497363-37ab9280-560f-11e9-81eb-271893372fb7.png)

**Comment by MichaelKohler** [comment]
and "Subscribe" would do what exactly? go to activate.mozilla.community/newsletter?

**Comment by MichaelKohler** [comment]
also, instead of a subscribe button we could just link the whole box, what do you think about that?

**Comment by LucyeoH** [comment]
So I think events would  go up here once they have their splash pages ready. So then the button would take them to the RSVP button for the campaign or to the splash page. So maybe we could call it "RSVP"?

**Comment by MichaelKohler** [comment]
In that case I'd say let's link the whole box to keep consistency (the other boxes are linked the same way)

**Comment by LucyeoH** [comment]
+1

**Comment by LucyeoH** [comment]
@MichaelKohler why was this closed?

**Comment by MichaelKohler** [comment]
Because it's implemented.

**Comment by LucyeoH** [comment]
Oh! Because we don't have any upcoming campaigns yet! Got it!

**Comment by MichaelKohler** [comment]
Yes, you or K will need to tell me if I need to add a campaign or upcoming campaign ;)
