### ISSUE TITLE
Add Google Analytics via Google Tag Manager (GA via GTM)

### ISSUE THREAD

**Issue by hmitsch** [mozilla/activate.mozilla.community#340]
In order to measure campaign impact, we would like to integrate Google Analytics via Google Tag Manager into the Activate Site. This allows us to see "click events". As usual, please remember to wrap this into a DNT clause.

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WHL2PP8');</script>
<!-- End Google Tag Manager -->
```

Thanks for all the awesomeness.
-Henrik

**Comment by MichaelKohler** [comment]
GTM is enabled, all outgoing link buttons (like the campaign buttons) are submitting info. Will now check out how we can get page views.

**Comment by MichaelKohler** [comment]
@hmitsch: I think this already works as expected, from what I can see in the console external button clicks as well as navigation within the page is already captured. You can probably remove the existing variable already as clicks on the campaign buttons as well as navigation is already being tracked without data layer.

Can you please close this issue if everything is working as expected?

**Comment by MichaelKohler** [comment]
@hmitsch quick ping here

**Comment by LucyeoH** [comment]
@MichaelKohler @hmitsch any update here?

**Comment by hmitsch** [comment]
Everything works as expected. 

![image](https://user-images.githubusercontent.com/869692/57459182-fee88400-7272-11e9-8fe6-b1359d78a1d0.png)


Thanks, Michael!
