### ISSUE TITLE
Enable locales even if they are not 95% complete

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#343]
I think we should activate locales even if they are not fully localized.

People might be interested in having just front page and the last active campaign done and don't care about the rest, we should enable that.

**Comment by MichaelKohler** [comment]
This sounds like a process change rather than code change. Sure, let's do that. Can we close? :P

**Comment by MichaelKohler** [comment]
(sure, the README needs to be updated, fair enough)

**Comment by nukeador** [comment]
@MichaelKohler I'm worried most localizers will never know they have to do an additional step to enable the locale and they have to request it via github (instead of pontoon where we point them).

Is there a way to avoid this manual request?

**Comment by MichaelKohler** [comment]
I'd argue most l10n at Mozilla has some kind of manual step to enable a language. We could do it automatically but then we need a trigger. The only trigger that comes to mind is "locale enabled on Pontoon" which says nothing about the progress. 

We can lazy load additional languages but in the end we would end up with quite a lot of languages with a few sentences translated. Not sure if that's what we want. Rhat specifically sounds like a programmatic question -> @couci

**Comment by MichaelKohler** [comment]
Also note that requesting the available languages from Pontoon might take time, so the availability of the user's preferred language the browser sends with the request might not be known for quite some. This means that on slow networks we would show English and then once that check is done, switch the user over to their preferred language. Possibly while the user is reading content on the website, depending on how long that check takes.

**Comment by couci** [comment]
@MichaelKohler is there a way where we can trigger exposure of translated content only in case that the whole page has been translated?
example: in german there is only the front page translated so have the front page translated but not the activities.
Note: if we do that we need a banner on top of those pages saying to people that this is not translated so we avoid false expectations.

**Comment by MichaelKohler** [comment]
That would require us to maintain a list of which strings are used on which page. And then we would need to have a script that cross-checks this with the translations that we have in the repo. That would be a very custom script. 

> example: in german there is only the front page translated so have the front page translated but not the activities.

That's what already would happen. Anything that is not translated is shown in English.

**Comment by nukeador** [comment]
I was talking with Peiying about this, and for other mozilla web properties they are enabling localization as they go, as proposed here. The only exception is mozilla.org because they are including full pages in a single string.

@couci If you don't have any flags I think we should now enable all languages that we have on pontoon.

**Comment by MichaelKohler** [comment]
I'd be fine with that, but we would still need a process about new languages being added. I'd rather not have them be queried on every single request but rather added to our repo. This needs a manual trigger and PR or an automatic script (and therefore a backend).

**Comment by nukeador** [comment]
@MichaelKohler Can we enable now all languages present over pontoon? We'll create a request for new languages so this doesn't need a backend.

https://pontoon.mozilla.org/projects/mozilla-activate/

Thanks!

**Comment by MichaelKohler** [comment]
Works for me, will do.
