### ISSUE TITLE
[Common Voice Activity] Add button linking to Common Voice website 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/activate.mozilla.community#344]
Hey All,

@nukeador  and I want to do a little experiment.  Can we:
1. Add a button (as seen below) that sends people to https://voice.mozilla.org
2. Use GA to know how many people click on the button. 
3. Use GA to know how many people click through the activity descriptions on the page. 

Then in 1 month, move the button to below the activity descriptions and track again to compare.

<img width="767" alt="Screen Shot 2019-04-09 at 10 32 02 AM" src="https://user-images.githubusercontent.com/8070833/55808788-c5c1c600-5ab2-11e9-932d-859d033d7b04.png">

**Comment by MichaelKohler** [comment]
We can tackle this once https://github.com/mozilla/activate.mozilla.community/issues/340 is done.

**Comment by LucyeoH** [comment]
Hey! Sounds like #340 is done. Might be good to sync with @nukeador and Lindsay on this too as part of the tracking for the experiment email.

**Comment by MichaelKohler** [comment]
@nukeador does the initial description still match what you'd like to do? Anything else?

**Comment by nukeador** [comment]
Yes, what do you need to know to set it up?

**Comment by MichaelKohler** [comment]
I don't think I need anything for now, I just need to send a GA event and then verify that we are actually getting it (will need help from someone who actually has access to GA).

**Comment by MichaelKohler** [comment]
Instead of creating tracking logic for this in the website, I think we could use GTM itself: https://www.wearefine.com/mingle/tracking-link-clicks-with-tag-manager-part-i-the-basics/

Then we just need to add the button and possibly with a link that has a utm query param or similar so we can identify it. 

@nukeador can you have a look at this? I don't have access to GTM.

**Comment by LucyeoH** [comment]
@MichaelKohler can we add the button to the CV activity even before we have GA setup? We've gotten more feedback lately that the activities don't have easy-to-access CTAs and I think this is a quick fix. :)

**Comment by MichaelKohler** [comment]
> @MichaelKohler can we add the button to the CV activity even before we have GA setup? We've gotten more feedback lately that the activities don't have easy-to-access CTAs and I think this is a quick fix. :)

Yes, I'll take care of this.

**Comment by MichaelKohler** [comment]
This is now done, including event when people click on it. @LucyeoH or @nukeador tell me when you want me to move it below the flow and I'll do it.

**Comment by LucyeoH** [comment]
You are a hero
