### ISSUE TITLE
Footer form, missing checkbox

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#347]
On the footer I think we are missing the checkbox to agree with the privacy policy

![imagen](https://user-images.githubusercontent.com/531906/58054764-e96d3700-7b5b-11e9-90b6-21a4d1e75fce.png)

**Comment by MichaelKohler** [comment]
yay, styling is hard. Will check what is wrong here.

**Comment by MichaelKohler** [comment]
@nukeador which browser did you test this with? I can't reproduce this in neither Firefox Nightly, Firefox Release nor Chrome.

**Comment by nukeador** [comment]
Beta under Linux

**Comment by MichaelKohler** [comment]
Fix should be deployed in a few minutes.
