### ISSUE TITLE
#MozActivate should link to new tweet

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#348]
In "Share your experience with #MozActivate"

Maybe #MozActivate should be a link to a new tweet with that hashtag already filled

http://twitter.com/home?status=This%20is%20my%20text%20%23MozActivate

**Comment by MichaelKohler** [comment]
Any chance we could just pass the hashtag as text? Then we don't need to worry about localization which would be quite a mess due to the encoding needed and possible placement inside the URL.

**Comment by nukeador** [comment]
AFAIK the text should be urlencoded, I don't know if that's what you are asking.
