### ISSUE TITLE
Idea to Showcase Impact in Activities

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#35]
From @rosanardila ...

I wanted to share some insights from when we redesigned the SUMO get involved pages: https://support.mozilla.org/en-US/get-involved (go to each "way to get involved" to see how they look like).

If you look at them they have little text in the front and they are a bit "inspiring" and showcase the impact. This is of course pretty old, but I think that having a "landing" page for each activity that gives you a short summary, 3 first steps and the impact that could help people get oriented quicker. Then you can add all the details on subpages.

It would be interesting to see if a more simplified and "campaign" approach could help!

**Comment by nukeador** [comment]
Yes, I fully support @rosanardila suggestion here. We need to be way more visual with the content we present to people.

**Comment by brianking** [comment]
![firefox_screenshot_2016-08-27t19-10-07 893z](https://cloud.githubusercontent.com/assets/114116/18029531/ba3686b2-6c9a-11e6-8907-bbe597508376.png)

Screenshot to illustrate what @rosanardila is talking about. I like:

* at the top it talks about the skills needed for the activity upfront
* it shows the potential impact (the part about "1 article can be viewed by 400 million users .....")

**Comment by brianking** [comment]
Check Open Innovation Toolkit site - https://toolkit.mozilla.org/
