### ISSUE TITLE
Link back to Mozilla.org from Footer

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/activate.mozilla.community#350]
It would be good to give people a pathway back to Mozilla.org. Perhaps adding to the footer: 

Company: 
* About (that links to mozilla.org)

(like the image but without press center or careers)

<img width="160" alt="Screen Shot 2019-05-22 at 10 52 15 AM" src="https://user-images.githubusercontent.com/8070833/58187449-c68a7200-7c84-11e9-939a-c0f573e19680.png">

Including @hoosteeno for other ideas.

**Comment by MichaelKohler** [comment]
.. or possibly in the header navigation as "mozilla.org"? Or maybe that's too prominent?

**Comment by stagedataloss** [comment]
test123

**Comment by LucyeoH** [comment]
@MichaelKohler I'd rather keep the header sending ppl back to the front page of activate.

**Comment by MichaelKohler** [comment]
@LucyeoH sorry, that was not clear. I mean something like the following, not sure if it's a good idea or not though.

<img width="699" alt="Screenshot 2019-05-29 at 21 25 44" src="https://user-images.githubusercontent.com/330324/58585209-9ecc7880-8247-11e9-8b00-da9808e322e6.png">

**Comment by LucyeoH** [comment]
Oh I don't think it needs to be THAT prominent. I actually chatted to Konstantina and it turns out there's already a template for how to do this in the footer that we have on the bottom of [the Activate template](https://events.mozilla.org/becomeabetatestingbughunter). 

Don't know why I didn't realize it earlier!

<img width="460" alt="Screen Shot 2019-05-30 at 11 49 17 AM" src="https://user-images.githubusercontent.com/8070833/58645287-0bd82080-82d1-11e9-86d5-876ca8c18f69.png">
