### ISSUE TITLE
The site doesn't speak to people who are interested in building and patching Firefox

### ISSUE THREAD

**Issue by hsivonen** [mozilla/activate.mozilla.community#351]
At present, https://activate.mozilla.community/ doesn't speak to people who are interested in learning how to build Firefox from source, modify the source, and submit a patch (especially if their expectations may have been set by other Open Source projects).

This is bad, because when contributing code is the most obvious kind of contribution to an Open Source project, conspicuously only listing contributions of other kinds than contributing code to the core piece of software that Mozilla is known for is tacitly suggestive of Mozilla not wishing to have code contributions to the core piece of software that Mozilla is known for. Such a suggestion seems unhealthy for an Open Source project.

On the most basic level, the front page of lacks a "Build Firefox from Source" box alongside "Using & Testing Nightly", "Dive Into Rust", etc. and instead buries the link that a person looking for the build instructions needs in the footer. (I only know about the footer because I suggested the link was not there and was told otherwise. I was unable to notice the link in the footer on my own.)

Additionally about the tone not speaking to people who are looking for build instructions: When the reader clicks the obviously-discoverable boxes (as opposed to locating the right link in the footer), the reader is exposed to content that is likely off-putting to person looking for the build instructions. While I have proper data only about my own feelings as an Open Source contributor, I expect the sidebars' transparency about the goals of the creators of the site that frame the reader as a data point in the site creators' success metrics and the non-sidebar text's treatment of the reader as someone to be directed in an "activity" as opposed to a person with agency looking for information on how to accomplish their own goal to be off-putting to people who otherwise would have potential to become code contributors to the Firefox codebase

As for how to fix, I suggest hoisting the link to https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Introduction from the footer (where it is undiscoverable in practice) to a box "Build Firefox from Source" on the same level as the "Using & Testing Nightly", "Dive Into Rust", etc. boxes. (I.e. linking the new box directly to https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Introduction without an intermediate page.)

**Comment by LucyeoH** [comment]
Hey - Thanks for this! We are currently gathering input and ideas for experiments to run on the activate site in H2! If you want to add even more ideas and feedback we have put together a [form here](https://docs.google.com/document/d/13O7Y3IwaY7kztC6SjJDp2z3gge8PcHlbS_FDpe86dWw/edit#heading=h.vv0fpyz35f03).

**Comment by LucyeoH** [comment]
We'll be addressing this through a new "evergreen" activity specifically for coding. See #353
