### ISSUE TITLE
Insert new evergreen activity "Code for Firefox" 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/activate.mozilla.community#353]
As an experiment #351 we want to make it easier for people to discover code contribution opportunities and measure how many people interact with it. 

Please add a new activity to the Activate site. 

Image: https://developer.mozilla.org/static/img/opengraph-logo.72382e605ce3.png
(If anyone has a suggestion of a better image please let us know!)

Text: Code for Firefox 

Link to: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Introduction

**Comment by MichaelKohler** [comment]
At which position?

**Comment by LucyeoH** [comment]
At the bottom is fine for now. Konstantina and I are auditing all the activities and will do a re-arrange later.
