### ISSUE TITLE
Split localization files per page

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#355]
It would be more productive for localizers to be able to see all the strings for a page in an individual file. This way they can prioritize the ones that are more important or identify where missing strings are.

This will also allow community managers to point to a specific activity page that needs to be covered.

homepage.ftl
faq.ftl
common-voice.ftl

...

**Comment by avelper** [comment]
Hi! I totally agree with this. Also, when only a few contents of the page are translated while the others are still in English, it doesn't look good from the users perspective. 

Thanks in advance!

**Comment by nukeador** [comment]
I've asked the localization team, and if we split files we would loose all suggestions in pontoon, attribution data in the db and history (e.g. if previous translations existed and were rejected).

Now, we can only add new strings in separate files, and hope to reduce the size of the main one with time.

There are currently 1K pending suggestions we can't risk losing.

@MichaelKohler ideas?

**Comment by MichaelKohler** [comment]
Oh, I see. Nope, no other solutions :(

**Comment by nukeador** [comment]
Can we do at least new string to new files so we start transitioning into that?

**Comment by MichaelKohler** [comment]
sure, let's close this and I'll keep this in mind.
