### ISSUE TITLE
Material links should be localized

### ISSUE THREAD

**Issue by lissyx** [mozilla/activate.mozilla.community#357]
Several links in the activate page points to elements that can be localized, including :
 - Discourse Common Voice section (there are some localized)
 - Slides (we should be able to localize them)
 - Instructions documents (we should be able to localize them)

**Comment by MichaelKohler** [comment]
That sounds reasonable, yes.

**Comment by MichaelKohler** [comment]
Discourse is blocked on https://github.com/mozilla/voice-web/issues/2070, so we have one single list of categories.

For Slides and instructions, the best way to do this would be to just link to a single folder with everything in it, see https://github.com/mozilla/activate.mozilla.community/issues/360

**Comment by MichaelKohler** [comment]
https://raw.githubusercontent.com/mozilla/voice-web/master/locales/discourse.json
