### ISSUE TITLE
Portuguese (pt-BR) Localization

### ISSUE THREAD

**Issue by alipseight** [mozilla/activate.mozilla.community#36]

**Comment by alipseight** [comment]
Traduzido a pasta [https://github.com/alipseight/activate.mozilla.community/blob/gh-pages/_data/l10n/pt-br.yml](url)

**Comment by nukeador** [comment]
Lang code should be just "pt"

**Comment by brianking** [comment]
Is this done?

**Comment by alipseight** [comment]
Yeah, i will review the texts and, if is correct, i'll close.

**Comment by deimidis** [comment]
@alipseight are you watching Brazil Discourse tracks? I want to ask for reviewers there too. All pages seems localized

**Comment by alipseight** [comment]
@deimidis 2 pages untranslated.

Done.

**Comment by alipseight** [comment]
@deimidis 2 pages untranslated.

Done.

**Comment by alipseight** [comment]
Hi, I'm reopen this issue because have a new localization to portuguese.

https://github.com/mozilla/activate.mozilla.community/pull/98

**Comment by alipseight** [comment]
The pull request have a conflict and don't show the problem.

**Comment by mchagas** [comment]
Hi people,

FYI, I'm localizing the new content from Activate pages. There are a lot of pages without localization to pt-BR and I'm assuming that project now. I'm talking with some volunteers on Mozilla Brasil Community to help me with localization and reviews. So in the next few days possibly you will receive a bunch of PR with the pages localized to pt-BR.

TY.
Cheers,

**Comment by mchagas** [comment]
Hey @brianking, just one more thing. I've noticed that the xliff are using lang tag pt-PT. All the work done here are pt-BR, there is a slightly difference, so, if you, or anyone who are working on system migration, don't mind could you correct this mistake? We from Mozilla Brasil Community will appreciate that.

TY.

Cheers,

**Comment by MichaelKohler** [comment]
Do I see this correctly that the only thing here is to change "pt-PT" to "pt-BR"?

**Comment by MichaelKohler** [comment]
This has now been done (including the change to pt-BR). Please track the progress of https://github.com/mozilla/activate.mozilla.community/issues/34 to see when they are available on pontoon. :)
