### ISSUE TITLE
Add Upcoming Campaign: Firefox For Good Contest

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/activate.mozilla.community#361]
Can you put this up as an upcoming campaign? 

https://events.mozilla.org/firefoxforgood-surfacingqualitycontentandconversat

**Comment by MichaelKohler** [comment]
@LucyeoH any prefered thumbnail image? And should I take the title and description from that page?

**Comment by LucyeoH** [comment]
Title: "Firefox For Good Competition" 
Thumbnail: https://pixabay.com/vectors/anatomy-biology-brain-thought-mind-1751201/

**Comment by LucyeoH** [comment]
@MichaelKohler Thanks SO much! Can we also add a "get involved" button?

**Comment by MichaelKohler** [comment]
@LucyeoH I thought we decided to link them the same way as we do the "past campaigns" so that whenever you click on the title or picture you get to the link?

**Comment by LucyeoH** [comment]
I feel like having a "get involved" or "RSVP" button makes it clear it's
something you should engage with now. Rather than the past campaigns that
you can visit but not meaningfully engage with. Thoughts?

**Comment by MichaelKohler** [comment]
Fair enough, the change is deploying and will be visible in a few minutes.

**Comment by LucyeoH** [comment]
You are, legitimately amazing. 
Here is an appreciative Drake gif - https://gph.is/g/aQNQYVb
