### ISSUE TITLE
Move locale bn-BD to bn

### ISSUE THREAD

**Issue by peiying2** [mozilla/activate.mozilla.community#364]
We are going to merge the two bn-* locales into one to fully utilize the community resources. The project has only bn-BD. We want to sync up with the rest of the localized products/projects. The plan is

Dev:
- Mozilla Activate creates a bn folder at repo
- Move bn-BD repo content to bn repo and confirm it's all there
- Remove bn-BD

Pontoon (l10n):
- Pontoon dev migrates the data to bn (this includes contributors histories)
- L10n PM confirms the update and closes this issue.

**Comment by peiying2** [comment]
@nukeador let know who I should assign this issue to.

**Comment by MichaelKohler** [comment]
@peiying2 This is done on my side
