### ISSUE TITLE
Add as an active campaign SOTI for December 16th

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/activate.mozilla.community#369]
On Monday 16 of December, the following text should be posted. Note that a link to the platform should be added in the last sentence. The platform should be available on Monday.

Activate Page - Blurb
Main Title:  Share your thoughts on the Surveillance Economy
Image:  https://unsplash.com/photos/fPxOowbR6ls
Photo Credit: Photo by [Matthew Henry](https://unsplash.com/@matthewhenry?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) 

Dates:   December 16th - January 2nd

Mozilla is evaluating how we might be bolder, broader and bigger in our work through the [open and transparent ‘State of the Internet’ project](https://wiki.mozilla.org/State_Of_The_Internet#Values). Outcomes will inform what longer horizon bets we might place to better address critical topics in online life. The project’s initial focus is on the [Surveillance Economy](https://wiki.mozilla.org/State_Of_The_Internet/Surveillance_Economy).

Share your insights on the [Surveillance Economy](https://wiki.mozilla.org/State_Of_The_Internet/Surveillance_Economy), by reviewing and commenting on these 3 provocations (NEED LINK TO PLATFORM)

**Comment by couci** [comment]
This is postoponed for tomorrow 17th December

**Comment by MichaelKohler** [comment]
This is (mostly) ready with limitations at https://github.com/mozilla/activate.mozilla.community/pull/377. Will need the platform URL before I can merge though.
