### ISSUE TITLE
Sunset the webextension activity

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#370]
We are working with @caitmuenster on having more impactful extensions activity on activate. One that can address both individual and group contributions.

Here are the steps to sunset:
- [ ] inform the community @couci 
- [ ] inform core volunteers @caitmuenster 
- [ ] take out the activity from activate @MichaelKohler 

On January 2020 @caitmuenster and @couci will work to have a more impactful activity on activate and in the future on the community portal

**Comment by MichaelKohler** [comment]
Tell me once you've informed the community and I'll remove it.

**Comment by caitmuenster** [comment]
Community leaders were notified by me on June 12, 2019.
