### ISSUE TITLE
Redirect Activities menu to the new activities in the community portal

### ISSUE THREAD

**Issue by couci** [mozilla/activate.mozilla.community#384]
When someone clicks on the menu activities could we direct them here: https://community.mozilla.org/activities/

**Comment by nukeador** [comment]
Is it me or for some reason now this link opens in a new tab?

**Comment by nukeador** [comment]
Also, is it possible to redirect https://activate.mozilla.community/activities/ to the new page?

**Comment by MichaelKohler** [comment]
> Is it me or for some reason now this link opens in a new tab?

Works for me.

> Also, is it possible to redirect https://activate.mozilla.community/activities/ to the new page?

In theory yes, in practice too much work for the benefit.
