### ISSUE TITLE
Content for Empower Developer Communities page

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#4]
Once we've designed the first activity, update this page with details.

Page to be edited:
https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_pages/developer-engagement.md

Live test:
https://mozilla.github.io/activate.mozilla.community/area/developer-engagement

**Comment by brianking** [comment]
All site copy for first launch being updated (WIP) here:

https://docs.google.com/document/d/1Qrl369msjfeDZMHaXBsQwdFjLfPWtWCSmBCkFBJI1jE/edit?usp=sharing

**Comment by nukeador** [comment]
We should link to the activity pages from the main initiative page.

**Comment by brianking** [comment]
Content added.

TODO: Link to the activities listed, right before launch.

**Comment by brianking** [comment]
Links to activities are now live.
