### ISSUE TITLE
Greyed out Rust and Web Privacy in activate.mozilla.com

### ISSUE THREAD

**Issue by gaby2300** [mozilla/activate.mozilla.community#41]
Windows 7 64 bit, today's Nightly.

When browsing to activate.mozilla.com, Rust and Web Privacy are greyed out and seem inactive.
I am including a screenshot for you to see.

![greyed out issue](https://cloud.githubusercontent.com/assets/2151784/17872071/c73074f4-6894-11e6-8cf7-ba82ffb93bc8.jpg)

**Comment by ioana-chiorean** [comment]
Hey @gaby2300 -  this is the intended behavior as those two initiatives are not ready/available yet.

**Comment by gaby2300** [comment]
Hi @ioana-chiorean and @nukeador, I filed this at Brian's request. I didn't know it was the intended behavior of course, sorry!
