### ISSUE TITLE
Create 2nd Wave Comms Plan

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#42]
Issue #11 was about the initial launch, now we need to create the 2nd wave comms plan to keep momentum going. 

One big question is whether and how we target beyond Reps.

**Comment by brianking** [comment]
Reps:

* Reach out directly to community mailing lists
* Talk 1-1 to regional loaders
* Reps Regional coaches
* Post again on social media (Twitter and Facebook)
* Reps Telegram

All:

* Mozillians Telegram
* All Mozillians mail (ask @LucyeoH)

Are we missing any?

**Comment by nukeador** [comment]
@brianking is this something we can have tomorrow? Where do you need help here?

**Comment by brianking** [comment]
It's basically outlined in the tasks above! I could use help with content.

**Comment by brianking** [comment]
We've had multiple comms by now, so closing this out.

I've opened #118 '2016 End of Year Activate Drive'.
