### ISSUE TITLE
Incentivization Techniques

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#43]
Gather a set of tactics for incentivizing participation in the campaign, evaluate, and roll out a couple of initial steps.

First step: talk to @LucyeoH about Campus Campaign tactics.

**Comment by brianking** [comment]
Some raw notes from an initial chat with @LucyeoH and @nukeador ...

* Add more information about why the focus area, e.g. Rust, of the activity is important to Mozilla.

* Look into how the contribute page tracks activities and creates a pipeline. Model will not directly move over because Activate activites require more time and some need to be done offline.

* The 'I did this' button on One and Done was not a success, most people used it after not doing the activity. People will always looks for ways to bypass and game the system.

* Leaderboards - MLS was very successful .... something to look into.

* Look into how teaching kits and the innovation toolkit are presented and see if we want to use any of their design and UX for activities

* Mike Hoye tried to do a points system for coding contributions, only got so far. We will touch base with him on lessons learned

For intrgration with the Contribute page, we agreed a good approach would be to direct people to Activate after completing a couple of lightweight activities. More discussion and  stakeholder feedback needed on this, and will look to role it out in next quarter after we've rolled out more activities and learned more how Activate is working.

**Comment by brianking** [comment]
Only first one seems feasible in short-term.

**Comment by geroter** [comment]
Why not do a basic "blog" style page with a manually built weekly leaderboard? Seems very doable.

**Comment by MichaelKohler** [comment]
This is currently being looked at (including making activities more appealing for volunteers)
