### ISSUE TITLE
Add-ons e10s Activity

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#45]
In association with the add-ons and 110s team, build out the already in progress activity for launch with the next set.

**Comment by iamVP7** [comment]
@brianking  Any doc related to WIP for this activity.

**Comment by brianking** [comment]
This has actually been put on hold until Q4 as the Add-ons team have changed their strategy on e10s and are not ready yet.

**Comment by brianking** [comment]
Shipped!

https://discourse.mozilla-community.org/t/new-activate-activities-and-other-changes/11360
