### ISSUE TITLE
Content for Privacy page

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#5]
Once we've designed the first activity, update this page with details.

Page to be edited:
https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_pages/privacy-policy.md

Live test:
https://mozilla.github.io/activate.mozilla.community/area/privacy-policy

**Comment by brianking** [comment]
All site copy for first launch being updated (WIP) here:

https://docs.google.com/document/d/1Qrl369msjfeDZMHaXBsQwdFjLfPWtWCSmBCkFBJI1jE/edit?usp=sharing

**Comment by brianking** [comment]
Not for launch.

**Comment by nukeador** [comment]
We need to start conversation here in preparation for Marker party EU

**Comment by brianking** [comment]
Site structure has changed, no longer relevant.
