### ISSUE TITLE
Hindi(hi) localization

### ISSUE THREAD

**Issue by amitkumarj441** [mozilla/activate.mozilla.community#50]

**Comment by brianking** [comment]
We're not accepting any more localizations right now as we figure out the best way to scale up with this. Thanks for the interest and keep checking back. Issue #34.

**Comment by MichaelKohler** [comment]
Sorry it took so long. After all this time, we now decided to go back to the old system so we don't block on any translations anymore. This means that the translations live in the GitHub repository here. You can get more information on how to localize in the README.

General flow:

* Fork this project
* Look at the following folders:
https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_pages/
https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_data/l10n/
https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_includes/
* If there is no subfolder for your locale, create one
* Copy the English files to the subfolder of your locale and start translating them, please note that strings can be in any of the above mentioned folders.
* Create a PR with your changes.
* We will then add the language to the language dropdown

Feel free to ping me for any questions you might have.

**Comment by amitkumarj441** [comment]
Hey @MichaelKohler,

Thanks for sharing this info.

I followed the above suggested flow toward the goal for our local language translation done and I already have an existing fork of this repo but I didn't find any of our locale in these folders instead I found [en.yml](https://github.com/amitkumarj441/activate.mozilla.community/blob/gh-pages/_data/l10n/en.yml) and I don't think that this could be of any help.

I have couple of questions on this thread, which are as follows :
 - Do I need to create subfolder of locale in all three folders our fork?
 - Do I follow your previous suggestion to #34 for translating EN to our locale? If their is any changes, let me know?

Cheers,
Amit Kumar Jaiswal

**Comment by MichaelKohler** [comment]
> I followed the above suggested flow toward the goal for our local language translation done and I already have an existing fork of this repo but I didn't find any of our locale in these folders instead I found en.yml and I don't think that this could be of any help.

Copy the en.yml to hi.yml and do your translations there.

> Do I need to create subfolder of locale in all three folders our fork?

You can take ES as example: https://github.com/mozilla/activate.mozilla.community/tree/gh-pages/_includes/es

As of now, only the activities.html needs to be translated per language from the _include folder. For the _pages you should add all English md files you want to translate to the subfolder. For the _data folder, see above. There only the hi.yml needs to exist.

> Do I follow your previous suggestion to #34 for translating EN to our locale? If their is any changes, let me know?

No, we're not going with Pontoon for now due to technical challenges on our side. For now, copy the relevant markdown pages to a subfolder "hi" and translate the markdown files there.

**Comment by shahbaz17** [comment]
Hi @MichaelKohler ,
Any update on this ? I would to work on this with my community members as they have pretty good understanding of Hindi and have been contributing to l10n.
@amitkumarj441 any update from your side ?

**Comment by MichaelKohler** [comment]
My previous comment is still accurate. Please also check the README (contains that info as well).

**Comment by Ryuno-Ki** [comment]
Maybe you need to check, whether your already existing fork is up-to-date enough.

**Comment by MichaelKohler** [comment]
We are currently working on a refresh of the Activate page. This project is in its early stages, but what I can say now is that localization improvements (Pontoon) will be a big part of it. I'm closing this as it will be considered in the refresh. Once we will talk about about what locales to enable to be translated we will revisit all localization issues in this repository, so there is no need to create a new request somewhere.
