### ISSUE TITLE
Resources Process for India

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#52]
Let's add something to the FAQ about the budget and swag process for India.

It is basically what @umeshagarwal proposed in issue #21 (also copied below), with the following clarifications:

* No-resource events are to be promoted first, and only exceptional events should get budget and swag.
* Sign off on swag design needs to happen before any is produced. We should aim for some general activate branding, to future-proof ourselves for the arrival of new activities. Note we are doing a separate Rust swag experiment in issue #48.
* All swag requests will be processed by the India review team. However, the requests must be filed in Bugzilla using the usual form
* All budget requests will need final approval from staff, after review from the India team
* Each event should have it's own separate Reps event page, budget request (if needed), and swag request (if needed).

*******************************************************************************

Proposal by @umeshagarwal...

1) Locally produced Swag for Events happening in India - Coordinated by Umesh and Our Logistic team which includes (Chandrakant and Prathmesh)
2) Direct Fast tract budget which is less than 150 USD. Budget more that 150 USD will go through the usual process. -Coordinated by Umesh and Our Logistic team which includes (Chandrakant and Prathmesh)

Latest Notes:

    We will start producing Swags from this week with priority on: -Empower developer communities( Dive Into Rust andWeb Compatibility Sprint) -Second week onwards we will follow the same process for the next topic: -Use and test experimental Firefox features and Maker Party

Swags we will be producing for each topic:
-Limited T-shirt, Round Stickers, Square Stickers, Lanyard, Buttons, Brochures.
-Separate Swag pack for seperate topics.
-We will use our own form and Keep @brianking as reviewer including us(Logistic Team).

Swag Pack:

    10-50 Participant -> (One T-shirt for Organizer, 50 Round Stickers, 10 Buttons, 10 Brochures, 5 Lanyard).
    50-100 Participant -> (Two T-shirt for Organizer, 100 Round Stickers, 20 Buttons, 20 Brochures, 10 Lanyard).
    100-150 Participant -> (Three T-shirt for Organizer, 150 Round Stickers, 30 Buttons, 30 Brochures, 15 Lanyard).
    150-300 Participant -> (Three T-shirt for Organizer, 250 Round Stickers, 50 Buttons, 50 Brochures, 20 Lanyard).

Courier/Packing&sending:
-We are partnering with a cheap vendor who will do the packing and take care of sending it though out India.

I already have 2000 USD which is okay for producing the swags for the whole campaign.
But for budget for events we will need funds allocated to us based on your priority of how much you want to allocate and how many events you are expecting through out the event.

**Comment by couci** [comment]
Hey all,
overall it seems good. Some comments:
- I don't see the need for lanyards and buttons on those events for me stickers and t-shirts are good enough
- the design should be based on the activities not based on the the campaign, for example rust stickers make more sense than mozactivate stickers
- we should remind that the event criteria stay the same, budget is only approved for:
 * Food for participants for an event over than 5 hours
 * Venue rental (in the case of the no other alternative)
 * Travel for expert on the field (currently allowed only for Rust events)

**Comment by brianking** [comment]
@couci I prefer the idea of campaign swag because we can use for event of all activity types. I agree some high profile activities like Rust should have their own swag, but not all (not the other 2 activities we have currently).

**Comment by umeshagarwal** [comment]
I agree with both @couci and @brianking  so have updated the details...

**Comment by umeshagarwal** [comment]
Target Events/Initiative : 150 + 

Swags Details:
Unisex T-shirt(Activate Mozilla) - 200 T-Shirt 
Activate Mozilla Sticker Sheet (8 Stickers each sheet)) - 200 Sheet 
Round Stickers of Rust - 2000 Stickers
Square Stickers(Other Topics if needed) - 1000
Mozilla Wordmark Stickers - 1000

Two types of swag pack:
-One Generic Swag pack for Activate Mozilla.
-One Swag pack for separate applicable topics like Rust.

We will use the regular Mozilla Swag request form for processing the request and Keep @brianking as reviewer including us(Logistic Team). 

Swag Pack:
10-50     Participant -> (One T-shirt for Organizer, 50 Topic Related Round Stickers like Rust / Mozilla Round Stickers, 5 Mozilla WordMark, 1 Activate Mozilla Sticker Sheet (8 Stickers each sheet)).

50-100   Participant -> (Two T-shirt for Organizer, 100 Topic Related Round Stickers like Rust / Mozilla Round Stickers, 10 Mozilla WordMark, 2 Activate Mozilla Sticker Sheet (8 Stickers each sheet)).

100-150 Participant -> (Two T-shirt for Organizer, 150 Topic Related Round Stickers like Rust / Mozilla Round Stickers, 10 Mozilla WordMark, 2 Activate Mozilla Sticker Sheet (8 Stickers each sheet)).

150-300 Participant ->  (Two/Three T-shirt for Organizer, 200 Topic Related Round Stickers like Rust / Mozilla Round Stickers, 15 Mozilla WordMark, 3 Activate Mozilla Sticker Sheet (8 Stickers each sheet)).

Courier/Packing & sending:
-We will use India Speed post Courier system which can deliver in 72 hours within India. Packing by vendor is very high so we decided to buy the packing materials and get the packaging done by volunteers.

I will share the budget details of Swag with @brianking 

Regards
Umesh Agarwal

**Comment by brianking** [comment]
Idea: Do experiment with small amount of events and measure effectiveness of use of swag. Consider A/B testing and so same number without swag.

**Comment by umeshagarwal** [comment]
noted @brianking

**Comment by brianking** [comment]
This is now finalised an documented in this blog post:

http://blog.mozillaindia.org/1736

Thanks everyone!
