### ISSUE TITLE
Social Links are Broken

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#53]
1. Not all paramaters are passed ... related to how we are using &amp;

2. #mozactivate hashtag is not being passed

**Comment by nukeador** [comment]
Probably we need to urlfy the full string to avoid params to be removed. Maybe jekyll has a filter for this?

Any help welcomed!

**Comment by nukeador** [comment]
https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_layouts/page.html

**Comment by nukeador** [comment]
Fix should be this one → https://github.com/mozilla/activate.mozilla.community/pull/54
