### ISSUE TITLE
Sign Copyright Petition Activity

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#55]
Make a new, simple, activity around:

https://www.changecopyright.org/

Can we track people coming in from our site?

**Comment by geroter** [comment]
What's the mobilizer activity here? This isn't a general contribute page ... it's something to get our mobilizers aligned.

**Comment by brianking** [comment]
Agreed it is too lightweight. I wonder if there is something we can "add-on" to it, such as (off the top of my head) something around bringing more awareness to your community about copyright, e.g. Copyright MozCoffee.

Once Maker Party starts we'll have a more solid mobilizer action or set of actions.

**Comment by brianking** [comment]
+ @LucyeoH 

Campus Clubs is doing this at https://campus.mozilla.community/activities/#protect

I'm curious Lucy if you are tracking this in some way? 

And as we have discussed how to keep mobilizers engaged now that Maker Party is ending, let's continue to explore options here.

**Comment by LucyeoH** [comment]
@brianking we just got tracking at this level but I was having trouble pulling up the data. I've emailed Nikos and Christos for additional support and will get back to you!

**Comment by brianking** [comment]
Assigned to @LucyeoH and @nukeador to decide is there is any copyright activity in 2017 that can translate into a mobilizer activity.

**Comment by nukeador** [comment]
This campaign is no longer active.
