### ISSUE TITLE
Change Activity Categories

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#56]
Talked to @LucyeoH about the possibility of aligning with the 3 big categories that will be used for the Mozilla Clubs site.

**Comment by brianking** [comment]
Teach
Build
Learn

... to align with https://campus.mozilla.community/activities/

**Comment by brianking** [comment]
Would like feedback from @bacharakis and @LucyeoH on whether these categories are final on the campus site and whether you think they make sense on activate.

**Comment by LucyeoH** [comment]
yes! Those are final - we'll share some graphics with you that you can use.

**Comment by LucyeoH** [comment]
They are final. Should we grab a meeting to chat more?

**Comment by brianking** [comment]
TODO:
* Landing pages for new categories
* Site map to to fit activities into new categories

Setup 15 mins with Lucy and Christos to finalise this.

**Comment by brianking** [comment]
My proposal for overhaul of the categories:

https://docs.google.com/document/d/1xKNDoVyO3VgJVdEVAp8ikS3A3lIOtjcRqilcZRQY4xo/edit?usp=sharing

Feedback requested from @nukeador @LucyeoH and @comzeradd .. thank you!

**Comment by brianking** [comment]
TO: Map existing activities to new categories.
