### ISSUE TITLE
Site Issues in Responsive Mode

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#57]
I see at least 3 issues

* [ ] Header navigation pushed the Mozilla link out of place. An ideal solution would be to have a hamburger menu
* [ ] Text starting 'Are you interested in other areas...' sits at the side, instead of underneath
* [ ] Blank section near the bottom

@comzeradd can you possibly help with this?

![screen shot 2016-09-06 at 19 01 17](https://cloud.githubusercontent.com/assets/114116/18283422/6ea4b278-7465-11e6-89bd-c27888a86cfb.png)
(first 2 issues illustrated)

![screen shot 2016-09-06 at 19 01 29](https://cloud.githubusercontent.com/assets/114116/18283436/7ed8b96e-7465-11e6-8f8d-b3d2cb02b08d.png)
(3rd issue illustrated)

**Comment by comzeradd** [comment]
We should switch in classic collapse/hamburger UI for the mobile view in order to fit the navbar.

Work in progress yet, but I started addressing the responsive problems of the website.

![mobile](https://cloud.githubusercontent.com/assets/939357/18511234/44c03104-7a8b-11e6-82de-5c2a1bb12797.png)
