### ISSUE TITLE
Get Metrics Data From Reps Portal

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#59]
We are created a dashboard to ensure we are hitting our targets for the campaign. See issue #47 for more details.

There are 3 things we are tracking on the portal:
1. When someone makes an event they can choose the 'MozActivate' initiative.
   From this we would like:
   a. the absolute number of events (per week and total, reported weekly)
   b. the number of unique people doing these events (total, reported weekly) - this is our 'Mobilizers hosting activities' metric
   c. a total of the number of attendees at these events (per week and total, reported weekly) - this is our 'Unique people mobilized' metric.
2. When reporting, you can choose MozActivate as the activity
   I'm not sure how useful this is, given the less than 100% reporting rate and the fact we can track via events opened.
3. When reporting, you can choose which activity you ran (MozActivate - ...).
   From this we would like:
   a. the number of each activity (per week and total, reported weekly)
   I see 2 problem here:
   a. Reps not being 100% consistent in reporting
   b. some events mix activities, and Reps may not feel inclined to file a more than one report for one event

One issue we see already is misreporting and I'm not sure how to solve for that. We can socialize more, but it might make a weekly check and manual fixes before each weekly report to mitigate.

I'm open to other ideas to change things if needed to get this data.

**Comment by hmitsch** [comment]
Discussed with Brian. We will pursue using analytics.mozilla.community for the reporting. @brianking will check how to approach Bitergia.

**Comment by brianking** [comment]
Blocked by https://github.com/mozilla/participation-metrics-org/issues/1 and https://github.com/mozilla/participation-metrics-org/issues/9.

We will have to do it manually for now.

**Comment by brianking** [comment]
Talked with @akatsoulas @comzeradd and @nukeador about this today and we agreed on an approach using the Reps API. For now, @akatsoulas and @comzeradd will look at the requested data in the first comment in this issue, and report back on what is feasible and if a simple weekly report can be automated and delivered.

**Comment by brianking** [comment]
Closing this as dupe of #47
