### ISSUE TITLE
Content for Experiments page

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#6]
Once we've designed the first activity, update this page with details.

Page to be edited:
https://github.com/mozilla/activate.mozilla.community/blob/gh-pages/_pages/test-pilot.md

Live test:
https://mozilla.github.io/activate.mozilla.community/area/test-pilot

**Comment by brianking** [comment]
All site copy for first launch being updated (WIP) here:

https://docs.google.com/document/d/1Qrl369msjfeDZMHaXBsQwdFjLfPWtWCSmBCkFBJI1jE/edit?usp=sharing

**Comment by nukeador** [comment]
We should link to the activity pages from the main initiative page.

**Comment by nukeador** [comment]
Also, should we rename the URL for this initiative? I see there is an activity under /firefox/

**Comment by brianking** [comment]
Yes, what are your thoughts? Do you think 'firefox' is ok?

**Comment by nukeador** [comment]
I would go for firefox-experiments or browser-experiements depending on the final name we are going to use for this initiative.

**Comment by brianking** [comment]
Content added.

TODO: Link to the activities listed, right before launch.

**Comment by brianking** [comment]
Links to activities are now live.
