### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#66]
Make a quick and dirty leaderboard of people running MozActivate events.

Potentially blocked by #59 

@comzeradd would like to hear your thoughts on how we could achieve this, both in terms of getting data and also displaying it on the site.

**Comment by brianking** [comment]
Open programmatic questions:

1. Do we want some extra validation step for events before they appear on the site? (to push outcomes, not # of events)
2. Do we want to give rewards? e.g. mozactivate hoodie to the winner every month

**Comment by brianking** [comment]
Temporarily blocked by Reps API changes.

**Comment by brianking** [comment]
Any update on this @comzeradd ?

**Comment by comzeradd** [comment]
The changes we needed on Reps API were implemented. I haven't planned working on this during this week. It would probably fit on our next week sprint.

**Comment by nukeador** [comment]
This leaderboard would be key to get more Reps involved as a social incentive

https://github.com/mozilla/participation-org/issues/468

**Comment by comzeradd** [comment]
I open a [PR](https://github.com/mozilla/activate.mozilla.community/pull/114).

**Comment by comzeradd** [comment]
Fixed at e6f65c42eebbad64f06ceed2062593d2aff9c3a2
