### ISSUE TITLE
Review Activity Sections

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#70]
Listed here are the current section headings in activities. We need to review to ensure that they are the best ones for full engagement. Are the terms clear? are there too little or too many? Are some of them optional for some activities?
- Introduction
- Impact and Metrics
  - Goals For This Area
- Audience For This Activity
- Activity Format / Event Flow
- Other Resources
- Output
- Extra

**Comment by AlexLakatos** [comment]
In some cases, *Activity Format* is an option between solo and a strongly encouraged event, but the *Event Flow* is the same for both. I think we could take advantage here and tailor a special "Tasks" section here for people that choose to go solo, instead of the Event Flow, which does not always apply for solo.

I think *Event Flow* should be more of a detailed checklist, with multiple items that need to be crossed in order, and with a definition of Done ™️

**Comment by emmairwin** [comment]
Hi, 

Some general feedback on the format of this activity and generally for activate.

**Find-ability** - It took a while to find the 'Activate Mozilla' website, Google didn't give it to me in the top searches ( I tried activity campaign Mozilla, activate Mozilla.  I also looked under participation in Discourse, but finally found it via search in Participation Leaders. The post themselves don't thin to a landing page, which makes it harder to 'look around' at other options.
**Appealing to Motivation** - On the actual  initiative page like Test Pilot, I would like to see a heading like 'why this matters to the web' or why this help's Mozilla's mission.  This is personal opinion that we should always, always reinforce why something someone is volunteering their time to do - is worth doing and will be enjoyable in some way.  You could also include 'skills you can build' in this activity, maybe even people you will meet.  Why not.
**Date & Progress** If we have a goal of 400 add-on tests, how can we track that progress as an individual community on that goal?  When does this initiative end?
**Linkage & Connection** - eventually it would be nice to link to community resources for things like 'put an event team together'.  Or even people you can ask for support.  IRC or Telegram channel.  I believe connection is one of the most powerful enablers in helping people feel established.
**Output** might also be 'share this activity on Twitter or other social channels with hashtag  "join me in helping Mozilla reach it's goals for x" #initiativename and help the web.    Something lower bar that can bring people in.
 **Examples/Media**.  Might be inspiring to link to examples embed a talk about  A-frame/web VR that can inspire people.  Seeing technology in action to grasp potential.

**Comment by brianking** [comment]
@comzeradd A couple of questions for you based on Emma's feedback:

1. Is there anything you can do to improve SEO?

2. Can we embed media in pages?

**Comment by nukeador** [comment]
Simple plugin for allowing youtube videos using clean markdown:

https://gist.github.com/serra/5574343

**Comment by emmairwin** [comment]
I used this short cut for videos in markdown https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#videos

**Comment by comzeradd** [comment]
For videos we could use the plugin @nukeador mentions or just plain html embed code (what youtube provides). You can use html inside markdown files without any problem and they get rendered properly.

Regarding SEO, I'm not an expert on the topic but in general what's important is the content. This is what the bots/crawlers fetch and analyze. On DuckDuckGo searching for `Activate Mozilla` it [gets first](https://duckduckgo.com/?q=activate+mozilla&t=h_&ia=web) (at least on me), but on Google is lower (~5th result). If we move this to our Analytics property we could have a better overview of what people search to reach the site or event add it to Google's Webmaster Tools for more. (/cc @hmitsch)

**Comment by couci** [comment]
considering the fact that activate is moving to a mobilizers tool thus not for activities playing solo, I think the current status serves the purpose for now
On the points that @emmairwin brought, @MichaelKohler could we add those on the improvements doc?

**Comment by MichaelKohler** [comment]
@couci that doc is not for content improvement. If you want to evaluate, let's discuss here in this issue or you can create a new doc. The only thing I see not being content is the find-ability. I'll create an issue for that one.

**Comment by couci** [comment]
I think linkage and output is something also that should be considered there

**Comment by MichaelKohler** [comment]
We can close this one as the current activities are quite similar and we want to allow for some individuality.
