### ISSUE TITLE
Event Best Practices Page

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#71]
To include such things as:
- Put an event team together
- Choose a date and secure a venue
- Give a thought whether it will be self-facilitated or with someone who has A-Frame experience. You can find help at the community page (https://aframe.io/community/)
- Setup the event on Reps Portal (https://wiki.mozilla.org/ReMo/SOPs/Event_hosting)
- Create an event page on a platform popular in your locale, such as Facebook, Meetup.com etc and keep posting interesting information about WebVR & related topics to keep the heat on.

As well as information on identifying your audience.

**Comment by couci** [comment]
this is already on the form that @brianking has built, I am closing this one

**Comment by brianking** [comment]
What form are you referring to @couci ? I still think this would be valuable to have. I can take it on to make a first pass if you wish.

**Comment by couci** [comment]
I thought this was referring to the activate template you've put together for the functional areas https://docs.google.com/document/d/11kEj9vfhAygSFzRvkVL5Wzmd7g1Vb8ySUjbH8RT3ln0/edit
Put an event team together
Choose a date and secure a venue
Setup the event on Reps Portal (instructions). Find a Rep closeby to do this if you are not one.

Except "the putting in your local famous platform" everything else is in there

**Comment by brianking** [comment]
Right, that is it, but the idea is to pull it out into a public page on the Activate portal. It is then something we can link to in activities, instead of having it repeated in multiple activities.

**Comment by couci** [comment]
@MichaelKohler what do you think? is there a place we can do that in the portal?

**Comment by MichaelKohler** [comment]
Sure, we can do a separate page for it.

**Comment by MichaelKohler** [comment]
@couci @brianking if you can provide the exact copy to include in a new page, we could go ahead with it

**Comment by couci** [comment]
@LucyeoH came up with a more full guide and now @francjp is on the reviewing mode to put more links into it. Once it is ready for review I will add it here for final feedback and put it on site

**Comment by MichaelKohler** [comment]
K to give us the content for the website.

**Comment by MichaelKohler** [comment]
Closing this one in favor of https://github.com/mozilla/activate.mozilla.community/issues/217
