### ISSUE TITLE
Timeline and Impact Activity Message Boxes

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#72]
For Activity pages, we should have ave the following highlighted at the top:
1. Timeline - how long the activity will last
2. Impact - why this is an important activity right now and the potential impact it can have.

I imagine these to be CSS boxes with different styling and a border applied, but am open to suggestions on how it is best implemented.

**Comment by comzeradd** [comment]
Yes, we could use simple distinct labels or even something closer to [this](https://chadsansing.github.io/eu-maker-party-sample-activites/updated-eu-maker-party-content/activity03-contribute-to-the-commons.html).

Do we have that info for all activities?

**Comment by brianking** [comment]
We don't have that info yet for all activities, but we can add one the capability is there.

**Comment by brianking** [comment]
Any updates on this @comzeradd ?

**Comment by comzeradd** [comment]
Would you images the timeboxes close to the screenshot below? Also, can you give me an example of Impact content?

![screen shot 2016-11-21 at 11 10 50](https://cloud.githubusercontent.com/assets/939357/20476795/72c54e1a-afdb-11e6-8e20-344379e51c36.png)

**Comment by brianking** [comment]
Yes, the timebox looks right. It is intended to show the **recommended time** to run the activity/event.

Here are the recommended times per activity:

- Dive Into Rust : 2-3 hours
- WebVR Camp : 3-4 hours
- Test Pilot : 2 Hours
- Web Compatibility Sprint : 2-3 Hours

**Comment by brianking** [comment]
And here are some proposed impact statements.

- Dive Into Rust : Having more developers understand, use and evangelize this language will advance make the web better and more secure.
- WebVR Camp : Having more developers and content creators playing with WebVR is important for the future of virtual reality to help build towards a free and open virtual reality platform not owned by any individual entity
- Test Pilot : By testing new features and functionality, you help to keep Firefox on the leading edge and consumers engaged in our product
- Web Compatibility Sprint : At Mozilla, we want the web running well for everyone, not just in one or two browsers. This means cross-browser, user-agent independent, and cross-device

**Comment by brianking** [comment]
We should consider also highlighting the value to contributors. But that is out of scope here, I will follow up in a separate issue about that.
