### ISSUE TITLE
Better 404 page

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#73]
Right now we just get the generic github pages 404. Can we customise this, and make sure a least a link to the home page exists?

**Comment by brianking** [comment]
Suggested text. I'd start with a quote:

"Not until we are lost do we begin to understand ourselves."
Henry David Thoreau

... and then just say something like: The page you were looking for does not exisiting. We suggest you <link>go the Activate home page</link> to find your way to where you are going. Good luck!

**Comment by brianking** [comment]
"does not exisiting" -> "does not exist". And make 'Activate home page'  a link.

**Comment by comzeradd** [comment]
[Done](https://activate.mozilla.community/404.html) :rocket:
