### ISSUE TITLE
Page Styles Not Loading

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#76]
All colours and styles have gone from the site pages, but image assets remain. This is what I see:

https://pageshot.net/O13hJvKOrw9MBi0D/activate.mozilla.community

**Comment by brianking** [comment]
Console shows me:


          GET 
https://activate.mozilla.community/activate.mozilla.community/asserts/css/bootstrap.min.css [HTTP/1.1 404 Not Found 99ms]
GET 
https://activate.mozilla.community/activate.mozilla.community/asserts/js/bootstrap.min.js [HTTP/1.1 404 Not Found 62ms]
GET 
https://activate.mozilla.community/activate.mozilla.community/asserts/js/app.js [HTTP/1.1 404 Not Found 41ms]

**Comment by comzeradd** [comment]
It's ok now. Now idea what caused it, but I removed base.url prepending since it's empty anyway on our `config.yml`.

I'm keeping this open to run a full check for dead links.

**Comment by comzeradd** [comment]
Run a full check and fixed all links
