### ISSUE TITLE
Page is not translated for ‘es’ and ‘fr’

### ISSUE THREAD

**Issue by teovermesan** [mozilla/activate.mozilla.community#84]
Steps to reproduce:
a. Go to https://activate.mozilla.community/
b. Go to the bottom of the page at the ‘Languages: en, es, fr, pt‘ option
c. Choose “es” or “fr”
Actual result:
- Page is not translated
Note:
- Choosing ‘pt’ will display the page translated

**Comment by nukeador** [comment]
We don't have yet the site translated into Spanish (WIP) and we probably will remove FR since we need to fix how the site handles localization before adding new locales.

**Comment by nukeador** [comment]
References: #14 #36
