### ISSUE TITLE
“Stay updated about new activities” option is missing for 'en' language 

### ISSUE THREAD

**Issue by teovermesan** [mozilla/activate.mozilla.community#85]
Steps to reproduce:
a. Go to https://activate.mozilla.community/
b. Go to the bottom of the page
Actual results:
-“Follow @MozParticipate on twitter” and “Subscribe to the Participation Leaders forum” are missing
Expected results:
- These 2 options should be present, since they are displayed for ‘es’, ‘fr’ and ‘pt’

**Comment by nukeador** [comment]
English site should have the updated content. We need to update es and pt.

**Comment by comzeradd** [comment]
Fixed at 2f638ad229b5cddfcb4db2d29457f6daf86275ef
