### ISSUE TITLE
Highlight Section on Homepage

### ISSUE THREAD

**Issue by brianking** [mozilla/activate.mozilla.community#92]
We talked about adding a highlighted section on the homepage to bring attention to more urgent things. Some uses of it would be:
- To add a CTA for Maker Party
- Highlight time-bound activities
- Highlight activities that need more engagement

**Comment by comzeradd** [comment]
I started experimenting with Maker Party graphics for this. Any ideas on the text we should include on the CTA?

**Comment by brianking** [comment]
Something like:

Maker Party is in full swing, and the focus this year is on copyright reform in the European Union. Help make a different to bring EU copyright laws up to date, to foster creativity and innovation on the Web. [Learn more](https://www.makerparty.community).
