### ISSUE TITLE
Frontpage links to specific sections

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#95]
Right now the frontpage themes link to the /activities/ page, where you have to scroll again to find the theme, we should probably link to the sections you clicked on like:

https://activate.mozilla.community/activities/#build-the-web

**Comment by comzeradd** [comment]
We can easily do that. Only problem with this approach is that you'll miss the intro text.

**Comment by nukeador** [comment]
@brianking maybe there is a way we can provide that info elsewhere?

**Comment by brianking** [comment]
One trick I see alot on sites is there is an arrow that people can click on to bring them to the top of the page. It also acts as a visual indicator that there is content above.
