### ISSUE TITLE
Icons on activities page

### ISSUE THREAD

**Issue by nukeador** [mozilla/activate.mozilla.community#96]
I feel we should use icons for the activities instead of the themes, so it's easier to visualize the different activities we have. Also move "Find out more" to a new line so it's easier to click in the same place for all blocks.

This would be my idea:

![captura de pantalla de 2016-10-25 13-33-47](https://cloud.githubusercontent.com/assets/531906/19684496/c0488a1e-9ab7-11e6-8371-6d162a31444c.png)

**Comment by brianking** [comment]
I'm not convinced. I think icons on categories is enough, and am wary of icon overload. Either way, the goal here is that both a) there is a clear distinction between categories, and b) the activities stand out. 

For me the bg colour on the activities, and the bold heading, make them stand out enough. Perhaps there are some other tricks we can do to bring them out more?

**Comment by brianking** [comment]
We should do this if we add tabbed categories ( #116  ), otherwise I would leave as is.

Thoughts @comzeradd ?

**Comment by MichaelKohler** [comment]
We are not using those icons anymore, therefore closing this issue.
